// src/ui/icons.js — consumption helpers for the pre-rendered tank icons in
// public/icons/ (generated by `node tools/genIcons.mjs` from the shipped
// models; regenerate after any tank-model change):
//   <id>_angle.webp           3/4 hero  -> garage carousel cards, tech tree
//   <id>_top.webp             top-down  -> tactical overlays
//   <id>_side.webp            side view -> detail panes
//   <id>_top_silhouette.png   flat white -> minimap blips (tinted green/red)
//   <id>_side_silhouette.png  flat white -> team panels, kill feed, damage panel
// Silhouettes ship as white fills so one file serves every team color.
// perf-r3c (Lighthouse): shaded views ship as WebP q90 — the PNG set weighed
// 214-237 KB per 512px icon and dominated page transfer. Silhouettes stay
// PNG: they are tiny flat alpha masks, and Chrome's canvas WebP encoder is
// lossy-only (lossy alpha rings on mask edges).

import { TANK_SPECS } from '../vehicles/specs.js';

const PUBLIC_BUILD = !!(import.meta.env && import.meta.env.VITE_PUBLIC_BUILD);

/** Public builds strip derivative renders of restricted recovered models.
 * Point those rows at the same legal family icon used by their procedural
 * visual fallback; private/local builds keep their exact generated icons. */
function distributableIconId(id) {
  if (!PUBLIC_BUILD) return id;
  const seen = new Set();
  let current = id;
  while (current && !seen.has(current)) {
    seen.add(current);
    const fallback = TANK_SPECS[current] && TANK_SPECS[current].publicVisualFallback;
    if (!fallback || fallback === current) break;
    current = fallback;
  }
  return current || id;
}

/** URL of a generated icon. @param {string} id tank id @param {string} view e.g. 'angle' */
export const iconUrl = (id, view) => `/icons/${distributableIconId(id)}_${view}.${
  view.includes('silhouette') ? 'png' : 'webp'}`;

const tintCache = new Map();

/**
 * Tinted silhouette as a canvas for per-frame 2D drawing (minimap blips).
 * Kicks off the image load on first request and returns null until ready —
 * callers draw their vector fallback in the meantime. Cached per id/view/color.
 * @param {string} id tank id
 * @param {string} view 'top_silhouette' | 'side_silhouette'
 * @param {string} color css color the white silhouette is tinted to
 * @returns {HTMLCanvasElement|null}
 */
export function tintedIcon(id, view, color) {
  const key = `${id}|${view}|${color}`;
  let e = tintCache.get(key);
  if (!e) {
    e = { c: null };
    tintCache.set(key, e);
    const img = new Image();
    img.onload = () => {
      const c = document.createElement('canvas');
      c.width = img.naturalWidth;
      c.height = img.naturalHeight;
      const x = c.getContext('2d');
      x.drawImage(img, 0, 0);
      x.globalCompositeOperation = 'source-in';
      x.fillStyle = color;
      x.fillRect(0, 0, c.width, c.height);
      e.c = c;
    };
    img.src = iconUrl(id, view);
  }
  return e.c;
}

/**
 * Turn a DOM element into a tinted silhouette via CSS mask: the element's
 * background color shows through the icon's alpha. Give the element explicit
 * width/height in CSS.
 * @param {HTMLElement} el
 * @param {string} id tank id
 * @param {string} view icon view name
 * @param {string} color css background color (the tint)
 */
export function maskIcon(el, id, view, color) {
  const u = `url(${iconUrl(id, view)})`;
  const s = el.style;
  s.webkitMaskImage = u; s.maskImage = u;
  s.webkitMaskSize = 'contain'; s.maskSize = 'contain';
  s.webkitMaskRepeat = 'no-repeat'; s.maskRepeat = 'no-repeat';
  s.webkitMaskPosition = 'center'; s.maskPosition = 'center';
  s.background = color;
}
