// GENERATED by tools/gen-authored-paint-catalog.mjs — do not edit by hand.
// Round 31/32 (owner 2026-09-20/21): every distinct authored paint in the fleet as a reusable catalog entry, named for
// its nation and pattern (never a vehicle); recipes that already exist as a named Signature / Service / national preset
// are not repeated, and scale / patch / cell knobs never split one paint into two.
// 13 entries over 62 vehicles.

export const AUTHORED_PAINT_IDS = Object.freeze([
  'paint_amx40',
  'paint_ares_apc_x',
  'paint_bmpt_terminator2',
  'paint_chieftain5',
  'paint_cv90_mkiv',
  'paint_griffin_viper',
  'paint_kurganets25_x',
  'paint_kv2',
  'paint_m1a1',
  'paint_strv81',
  'paint_t72b3m',
  'paint_t90ms',
  'paint_type74',
] as const);

export type AuthoredPaintId = typeof AUTHORED_PAINT_IDS[number];

export interface AuthoredPaintEntry {
  readonly id: AuthoredPaintId;
  readonly lead: string;
  readonly sourceTankIds: readonly string[];
  readonly nation: string | null;
  readonly label: string;
  readonly tags: readonly string[];
  readonly visual: {
    readonly scheme: string; readonly base: string; readonly weather: string; readonly patches: readonly string[];
    readonly camoScale?: number; readonly patchK?: number; readonly digitalCellK?: number; readonly solidWeatheringIntensity?: number;
  };
}

export const AUTHORED_PAINT_ENTRIES: readonly AuthoredPaintEntry[] = Object.freeze([
  {id: 'paint_amx40',lead: 'amx40',sourceTankIds: ['amx40','amx40_x'],nation: 'France',label: 'French Plain Khaki',tags: ['fr','desert','geometric','signature'],visual: {scheme: 'solid',base: '#96835a',weather: '#a4916a',patches: []}},
  {id: 'paint_ares_apc_x',lead: 'ares_apc_x',sourceTankIds: ['ares_apc_x'],nation: 'UK',label: 'British Three-Tone Woodland',tags: ['uk','woodland','organic','signature'],visual: {scheme: 'nato',base: '#4e5940',weather: '#60694f',patches: ['#252a22','#544233','#72745d'],camoScale: 0.44}},
  {id: 'paint_bmpt_terminator2',lead: 'bmpt_terminator2',sourceTankIds: ['bmpt_terminator2'],nation: 'Russia',label: 'Russian Digital Woodland',tags: ['ru','woodland','digital','signature'],visual: {scheme: 'digital',base: '#35452f',weather: '#3f4d36',patches: ['#243128','#4d4a37','#5a523e'],camoScale: 0.5,solidWeatheringIntensity: 0.03}},
  {id: 'paint_chieftain5',lead: 'chieftain5',sourceTankIds: ['chieftain5','chieftain_mk10','vickers_mk1','centurion3','centurion5','chieftain_mk10_x','chieftain5_x'],nation: 'UK',label: 'British Bands Woodland',tags: ['uk','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#3f4a36',weather: '#4a5540',patches: ['#1d1f1c','#33402c'],camoScale: 0.55}},
  {id: 'paint_cv90_mkiv',lead: 'cv90_mkiv',sourceTankIds: ['cv90_mkiv','cv90_mkiv_x'],nation: 'Sweden',label: 'Swedish Splinter Woodland',tags: ['se','woodland','digital','signature'],visual: {scheme: 'splinter',base: '#3c4739',weather: '#525c49',patches: ['#202823','#657251','#303c32'],camoScale: 0.82}},
  {id: 'paint_griffin_viper',lead: 'griffin_viper',sourceTankIds: ['griffin_viper'],nation: 'USA',label: 'US Army Three-Tone Woodland II',tags: ['usa','woodland','organic','signature'],visual: {scheme: 'nato',base: '#555d42',weather: '#777864',patches: ['#343a32','#827756'],camoScale: 0.5}},
  {id: 'paint_kurganets25_x',lead: 'kurganets25_x',sourceTankIds: ['kurganets25_x'],nation: 'Russia',label: 'Russian Digital Woodland II',tags: ['ru','woodland','digital','signature'],visual: {scheme: 'russian-digital',base: '#58634b',weather: '#6a705d',patches: ['#333c32','#76725a','#444b3d'],camoScale: 0.72}},
  {id: 'paint_kv2',lead: 'kv2',sourceTankIds: ['kv2'],nation: 'USSR',label: 'Soviet Plain Forest Green',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#37412a',weather: '#404b33',patches: []}},
  {id: 'paint_m1a1',lead: 'm1a1',sourceTankIds: ['m1a1','m1a1ha','m1a2','m1a2_tusk','m1a2_sepv2','m1a2_sepv3','t62mv1','cv90105_tml_x','m2a2_bradley','leo1a5','leopard2_proto','leo2a4','leo2a5','leo2a6','leo2_revolution_proto','leo2_revolution','leo2a7v','kf51','fv510','fv510_milan','fv510_milan_x','m60a1','sabra_mk2_x','amx30','amx30b2','m48','m60a2','m46_patton','m47_patton','m60a3','leo2a7v_x','leo2a5_x','kf51_x','leo2a6_x','amx30_x','t62mv1_x','m1a2_x','m1a2_tusk_x','m1a2_sepv2_x','m1a2_sepv3_x'],nation: 'USA',label: 'US Army Three-Tone Woodland',tags: ['usa','woodland','organic','signature'],visual: {scheme: 'nato',base: '#49543c',weather: '#525f45',patches: ['#23261f','#4a3a2c'],camoScale: 0.5}},
  {id: 'paint_strv81',lead: 'strv81',sourceTankIds: ['strv81'],nation: 'Sweden',label: 'Swedish Woodland',tags: ['se','woodland','organic','signature'],visual: {scheme: 'woodland',base: '#39483b',weather: '#4f5948',patches: ['#263129','#62634a','#74664c'],camoScale: 0.55}},
  {id: 'paint_t72b3m',lead: 't72b3m',sourceTankIds: ['t72b3m','t72b3m_x'],nation: 'Russia',label: 'Russian Plain Deep Green',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#293a28',weather: '#2e422d',patches: [],solidWeatheringIntensity: 0.03}},
  {id: 'paint_t90ms',lead: 't90ms',sourceTankIds: ['t90ms','t90ms_x'],nation: 'USSR/Russia',label: 'Russian Plain Brown',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#6a6047',weather: '#75694e',patches: []}},
  {id: 'paint_type74',lead: 'type74',sourceTankIds: ['type74'],nation: 'Japan',label: 'JGSDF Bands Woodland',tags: ['jp','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#44503a',weather: '#4e5a44',patches: ['#4d4133','#37432f'],camoScale: 0.6}},
]);
