// GENERATED by tools/gen-authored-paint-catalog.mjs — do not edit by hand.
// Round 31 (owner 2026-09-20): every distinct authored paint recipe in the fleet as a reusable catalog entry, named
// after its lead vehicle; recipes that already exist as a named Signature / Service preset are not repeated.
// 44 entries over 119 vehicles.

export const AUTHORED_PAINT_IDS = Object.freeze([
  'paint_amx40',
  'paint_ares_apc_x',
  'paint_ariete',
  'paint_bmp2',
  'paint_bmp3',
  'paint_bmpt_terminator2',
  'paint_carro45t',
  'paint_challenger1',
  'paint_chieftain5',
  'paint_cv90',
  'paint_cv90_mkiv',
  'paint_fv4034',
  'paint_isu122s',
  'paint_jpz_e100',
  'paint_kf51',
  'paint_kurganets25_x',
  'paint_kv2',
  'paint_leo2a5',
  'paint_leo2a5_a5nl',
  'paint_m1a1',
  'paint_m1a3',
  'paint_m26_pershing',
  'paint_m3a3_bradley',
  'paint_m551a1_tts',
  'paint_panther_g',
  'paint_spz_puma',
  'paint_spz_puma_s1',
  'paint_stb1',
  'paint_strv103',
  'paint_strv103a',
  'paint_strv81',
  'paint_sturmtiger',
  'paint_t14',
  'paint_t64bv1',
  'paint_t72b3m',
  'paint_t72bu',
  'paint_t90ms',
  'paint_t95',
  'paint_tiger1',
  'paint_type74',
  'paint_type89',
  'paint_type89_light_tiger',
  'paint_udes03',
  'paint_vt4a1',
] as const);

export type AuthoredPaintId = typeof AUTHORED_PAINT_IDS[number];

export interface AuthoredPaintEntry {
  readonly id: AuthoredPaintId;
  readonly lead: string;
  readonly sourceTankIds: readonly string[];
  readonly nation: string | null;
  readonly label: string;
  readonly tags: readonly string[];
  readonly visual: {
    readonly scheme: string; readonly base: string; readonly weather: string; readonly patches: readonly string[];
    readonly camoScale?: number; readonly patchK?: number; readonly digitalCellK?: number; readonly solidWeatheringIntensity?: number;
  };
}

export const AUTHORED_PAINT_ENTRIES: readonly AuthoredPaintEntry[] = Object.freeze([
  {id: 'paint_amx40',lead: 'amx40',sourceTankIds: ['amx40','amx40_x'],nation: 'France',label: 'AMX-40 Prototype Plain',tags: ['fr','desert','geometric','signature'],visual: {scheme: 'solid',base: '#96835a',weather: '#a4916a',patches: []}},
  {id: 'paint_ares_apc_x',lead: 'ares_apc_x',sourceTankIds: ['ares_apc_x'],nation: 'UK',label: 'Ares APC Tri-Tone',tags: ['uk','woodland','organic','signature'],visual: {scheme: 'nato',base: '#4e5940',weather: '#60694f',patches: ['#252a22','#544233','#72745d'],camoScale: 0.44}},
  {id: 'paint_ariete',lead: 'ariete',sourceTankIds: ['ariete'],nation: 'Italy',label: 'C1 Ariete Preserie Stripes',tags: ['it','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#42503a',weather: '#4c5a44',patches: ['#37432f','#2c352a'],camoScale: 0.6}},
  {id: 'paint_bmp2',lead: 'bmp2',sourceTankIds: ['bmp2'],nation: 'USSR',label: 'BMP-2 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#4a5138',weather: '#565e43',patches: []}},
  {id: 'paint_bmp3',lead: 'bmp3',sourceTankIds: ['bmp3','bmp3m_dragun125_x'],nation: 'Russia',label: 'BMP-3 Stripes',tags: ['ru','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#44503a',weather: '#525c45',patches: ['#2a331f','#5c5a41'],camoScale: 0.55}},
  {id: 'paint_bmpt_terminator2',lead: 'bmpt_terminator2',sourceTankIds: ['bmpt_terminator2'],nation: 'Russia',label: 'BMPT Terminator 2 Digital',tags: ['ru','woodland','digital','signature'],visual: {scheme: 'digital',base: '#35452f',weather: '#3f4d36',patches: ['#243128','#4d4a37','#5a523e'],camoScale: 0.5,solidWeatheringIntensity: 0.03}},
  {id: 'paint_carro45t',lead: 'carro45t',sourceTankIds: ['carro45t'],nation: 'Italy',label: 'Carro 45t Plain',tags: ['it','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#53604a',weather: '#5f6b55',patches: []}},
  {id: 'paint_challenger1',lead: 'challenger1',sourceTankIds: ['challenger1','challenger2','challenger1_x'],nation: 'UK',label: 'Challenger 1 Mk 2 Stripes',tags: ['uk','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#3f4a36',weather: '#48533e',patches: ['#1d1f1c'],camoScale: 0.45}},
  {id: 'paint_chieftain5',lead: 'chieftain5',sourceTankIds: ['chieftain5','chieftain_mk10','vickers_mk1','centurion3','centurion5','chieftain_mk10_x','chieftain5_x'],nation: 'UK',label: 'Chieftain Mk 3 Stripes',tags: ['uk','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#3f4a36',weather: '#4a5540',patches: ['#1d1f1c','#33402c'],camoScale: 0.55}},
  {id: 'paint_cv90',lead: 'cv90',sourceTankIds: ['cv90','ajax_x','k21_x'],nation: 'Sweden',label: 'CV90 Stripes',tags: ['se','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#3f4938',weather: '#535c49',patches: ['#273028','#59604a'],camoScale: 0.72}},
  {id: 'paint_cv90_mkiv',lead: 'cv90_mkiv',sourceTankIds: ['cv90_mkiv','cv90_mkiv_x'],nation: 'Sweden',label: 'CV90 Mk 4 Splinter',tags: ['se','woodland','digital','signature'],visual: {scheme: 'splinter',base: '#3c4739',weather: '#525c49',patches: ['#202823','#657251','#303c32'],camoScale: 0.82}},
  {id: 'paint_fv4034',lead: 'fv4034',sourceTankIds: ['fv4034'],nation: 'UK',label: 'FV4034 Plain',tags: ['uk','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#46523a',weather: '#566146',patches: []}},
  {id: 'paint_isu122s',lead: 'isu122s',sourceTankIds: ['isu122s'],nation: 'USSR',label: 'ISU-122S Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#5a6054',weather: '#666c60',patches: []}},
  {id: 'paint_jpz_e100',lead: 'jpz_e100',sourceTankIds: ['jpz_e100','jpz_e100_x'],nation: 'Germany',label: 'Jagdpanzer E100 Prototype Tri-Tone',tags: ['de','woodland','organic','signature'],visual: {scheme: 'nato',base: '#4c5740',weather: '#59634b',patches: ['#242820','#57463a'],camoScale: 0.48}},
  {id: 'paint_kf51',lead: 'kf51',sourceTankIds: ['kf51','kf51_x'],nation: 'Germany',label: 'KF51 EVO Tri-Tone',tags: ['de','woodland','organic','signature'],visual: {scheme: 'nato',base: '#49543c',weather: '#515e44',patches: ['#23261f','#4a3a2c'],camoScale: 0.34,patchK: 1.75}},
  {id: 'paint_kurganets25_x',lead: 'kurganets25_x',sourceTankIds: ['kurganets25_x'],nation: 'Russia',label: 'Kurganets-25 Digital',tags: ['ru','woodland','digital','signature'],visual: {scheme: 'russian-digital',base: '#58634b',weather: '#6a705d',patches: ['#333c32','#76725a','#444b3d'],camoScale: 0.72}},
  {id: 'paint_kv2',lead: 'kv2',sourceTankIds: ['kv2'],nation: 'USSR',label: 'KV-2 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#37412a',weather: '#404b33',patches: []}},
  {id: 'paint_leo2a5',lead: 'leo2a5',sourceTankIds: ['leo2a5','leo2a6','leo2_revolution_proto','leo2_revolution','leo2a7v','leo2a7v_x','leo2a5_x','leo2a6_x'],nation: 'Germany',label: 'Leopard 2A4 V Tri-Tone',tags: ['de','woodland','organic','signature'],visual: {scheme: 'nato',base: '#49543c',weather: '#515e44',patches: ['#23261f','#4a3a2c'],camoScale: 0.5}},
  {id: 'paint_leo2a5_a5nl',lead: 'leo2a5_a5nl',sourceTankIds: ['leo2a5_a5nl'],nation: 'Germany',label: 'Leopard 2A4M Stripes',tags: ['de','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#465041',weather: '#626b58',patches: ['#273229','#625a42','#78715c'],camoScale: 0.39}},
  {id: 'paint_m1a1',lead: 'm1a1',sourceTankIds: ['m1a1','m1a1ha','m1a2','m1a2_tusk','m1a2_sepv2','m1a2_sepv3','t62mv1','cv90105_tml_x','m2a2_bradley','leo1a5','leopard2_proto','leo2a4','m1a2_legacy','fv510','fv510_milan','fv510_milan_x','m60a1','sabra_mk2_x','amx30','amx30b2','m48','m60a2','m46_patton','m47_patton','m60a3','amx30_x','t62mv1_x','m1a2_x','m1a2_tusk_x','m1a2_sepv2_x','m1a2_sepv3_x'],nation: 'USA',label: 'M1A1 Abrams Tri-Tone',tags: ['usa','woodland','organic','signature'],visual: {scheme: 'nato',base: '#49543c',weather: '#525f45',patches: ['#23261f','#4a3a2c'],camoScale: 0.5}},
  {id: 'paint_m1a3',lead: 'm1a3',sourceTankIds: ['m1a3'],nation: 'USA',label: 'M1A3 Abrams Plain',tags: ['usa','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#464b3c',weather: '#555b49',patches: []}},
  {id: 'paint_m26_pershing',lead: 'm26_pershing',sourceTankIds: ['m26_pershing','m45_patton'],nation: 'USA',label: 'M26 Pershing Plain',tags: ['usa','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#3f4423',weather: '#54543e',patches: []}},
  {id: 'paint_m3a3_bradley',lead: 'm3a3_bradley',sourceTankIds: ['m3a3_bradley'],nation: 'USA',label: 'M3A3 Bradley CFV Tri-Tone',tags: ['usa','woodland','organic','signature'],visual: {scheme: 'nato',base: '#4a553d',weather: '#535f46',patches: ['#232620','#4b3b2d'],camoScale: 0.5}},
  {id: 'paint_m551a1_tts',lead: 'm551a1_tts',sourceTankIds: ['m551a1_tts'],nation: 'USA',label: 'M551A1 TTS Tri-Tone',tags: ['usa','woodland','organic','signature'],visual: {scheme: 'nato',base: '#4b5740',weather: '#687054',patches: ['#252d22','#6b5940'],camoScale: 0.88}},
  {id: 'paint_panther_g',lead: 'panther_g',sourceTankIds: ['panther_g'],nation: 'Germany',label: 'Panther Ausf. G Ambush',tags: ['de','desert','organic','signature'],visual: {scheme: 'ambush',base: '#8d7a4a',weather: '#80704a',patches: ['#6a713f','#7a4a35'],camoScale: 0.55}},
  {id: 'paint_spz_puma',lead: 'spz_puma',sourceTankIds: ['spz_puma','griffin50_x','kf41_lynx_x'],nation: 'Germany',label: 'Schützenpanzer Puma Tri-Tone',tags: ['de','woodland','organic','signature'],visual: {scheme: 'nato',base: '#46503c',weather: '#505a46',patches: ['#22251f','#4f4030'],camoScale: 0.5}},
  {id: 'paint_spz_puma_s1',lead: 'spz_puma_s1',sourceTankIds: ['spz_puma_s1'],nation: 'Germany',label: 'Schützenpanzer Puma S1 Tri-Tone',tags: ['de','woodland','organic','signature'],visual: {scheme: 'nato',base: '#46503c',weather: '#59604b',patches: ['#20231f','#514031'],camoScale: 0.72}},
  {id: 'paint_stb1',lead: 'stb1',sourceTankIds: ['stb1'],nation: 'Japan',label: 'STB-1 Plain',tags: ['jp','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#3c4937',weather: '#59624d',patches: []}},
  {id: 'paint_strv103',lead: 'strv103',sourceTankIds: ['strv103'],nation: 'Sweden',label: 'Stridsvagn 103B Splinter',tags: ['se','woodland','digital','signature'],visual: {scheme: 'splinter',base: '#384b3d',weather: '#4e5b49',patches: ['#263329','#62644b','#776b50'],camoScale: 0.48}},
  {id: 'paint_strv103a',lead: 'strv103a',sourceTankIds: ['strv103a'],nation: 'Sweden',label: 'Stridsvagn 103A Plain',tags: ['se','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#46503b',weather: '#525a44',patches: []}},
  {id: 'paint_strv81',lead: 'strv81',sourceTankIds: ['strv81'],nation: 'Sweden',label: 'Stridsvagn 81 Woodland',tags: ['se','woodland','organic','signature'],visual: {scheme: 'woodland',base: '#39483b',weather: '#4f5948',patches: ['#263129','#62634a','#74664c'],camoScale: 0.55}},
  {id: 'paint_sturmtiger',lead: 'sturmtiger',sourceTankIds: ['sturmtiger','isu152'],nation: 'Germany',label: 'Sturmtiger Plain',tags: ['de','desert','geometric','signature'],visual: {scheme: 'solid',base: '#8d7a4a',weather: '#7e6e44',patches: []}},
  {id: 'paint_t14',lead: 't14',sourceTankIds: ['t14','t14_x'],nation: 'Russia',label: 'Object 148 Proto Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#39442e',weather: '#42503a',patches: []}},
  {id: 'paint_t64bv1',lead: 't64bv1',sourceTankIds: ['t64bv1','t72b_1987_x','t72b3_x'],nation: 'USSR/Russia',label: 'T-64BV1 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#42513a',weather: '#4e5c45',patches: []}},
  {id: 'paint_t72b3m',lead: 't72b3m',sourceTankIds: ['t72b3m','t72b3m_x'],nation: 'Russia',label: 'T-72B3M obr. 2016 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#293a28',weather: '#2e422d',patches: [],solidWeatheringIntensity: 0.03}},
  {id: 'paint_t72bu',lead: 't72bu',sourceTankIds: ['t72bu','t90','t90a','t90a_vladimir','t90a_burlak','t90sm','t90m','t90m_proryv','t90a_x','t90a_vladimir_x','t90m_x','t90sm_x','t72bu_x','t90_x','t90a_burlak_x'],nation: 'USSR/Russia',label: 'T-72BU obr. 1989 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#3f5138',weather: '#4a5c42',patches: []}},
  {id: 'paint_t90ms',lead: 't90ms',sourceTankIds: ['t90ms','t90ms_x'],nation: 'USSR/Russia',label: 'T-90MS obr. 2011 Plain',tags: ['ru','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#6a6047',weather: '#75694e',patches: []}},
  {id: 'paint_t95',lead: 't95',sourceTankIds: ['t95'],nation: 'USA',label: 'T95 Plain',tags: ['usa','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#4b5320',weather: '#6b6b47',patches: []}},
  {id: 'paint_tiger1',lead: 'tiger1',sourceTankIds: ['tiger1'],nation: 'Germany',label: 'Tiger I Stripes',tags: ['de','desert','stripes','signature'],visual: {scheme: 'stripes',base: '#8d7a4a',weather: '#7e6e44',patches: ['#5c6a3b','#6f4a32'],camoScale: 0.6}},
  {id: 'paint_type74',lead: 'type74',sourceTankIds: ['type74'],nation: 'Japan',label: 'Type 74 Stripes',tags: ['jp','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#44503a',weather: '#4e5a44',patches: ['#4d4133','#37432f'],camoScale: 0.6}},
  {id: 'paint_type89',lead: 'type89',sourceTankIds: ['type89'],nation: 'Japan',label: 'Type 89 IFV Stripes',tags: ['jp','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#3a4739',weather: '#455245',patches: ['#5f4f3a','#2d382e'],camoScale: 0.5}},
  {id: 'paint_type89_light_tiger',lead: 'type89_light_tiger',sourceTankIds: ['type89_light_tiger'],nation: 'Japan',label: 'Type 89 Light Tiger Stripes',tags: ['jp','woodland','stripes','signature'],visual: {scheme: 'stripes',base: '#39473a',weather: '#4b5747',patches: ['#65523a','#26352d'],camoScale: 0.62}},
  {id: 'paint_udes03',lead: 'udes03',sourceTankIds: ['udes03'],nation: 'Sweden',label: 'UDES 03 Plain',tags: ['se','woodland','geometric','signature'],visual: {scheme: 'solid',base: '#45513f',weather: '#55614d',patches: []}},
  {id: 'paint_vt4a1',lead: 'vt4a1',sourceTankIds: ['vt4a1'],nation: 'China',label: 'VT-4A1 Digital',tags: ['cn','woodland','digital','signature'],visual: {scheme: 'digital',base: '#4b563a',weather: '#59644b',patches: ['#6f6b4b','#313b2b','#242820'],camoScale: 0.46}},
]);
