// Generated by tools/gen-combat-anatomy.mjs. Do not hand-edit.
// Main armor and internal volumes are calibrated to these first-party geometry receipts.
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_ABRAMS } from './combatAnatomyGroups/abrams.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_AFV } from './combatAnatomyGroups/afv.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_CASEMATE } from './combatAnatomyGroups/casemate.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_CHALLENGER } from './combatAnatomyGroups/challenger.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_CORE } from './combatAnatomyGroups/core.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_FRANCECORE } from './combatAnatomyGroups/franceCore.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_GERMANY } from './combatAnatomyGroups/germany.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_ITALY } from './combatAnatomyGroups/italy.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_JAPAN } from './combatAnatomyGroups/japan.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_KOREA } from './combatAnatomyGroups/korea.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_LEOPARD } from './combatAnatomyGroups/leopard.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_MERKAVA } from './combatAnatomyGroups/merkava.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_MISC } from './combatAnatomyGroups/misc.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_MODERN2 } from './combatAnatomyGroups/modern2.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_MODERN3CORE } from './combatAnatomyGroups/modern3Core.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_PATTON } from './combatAnatomyGroups/patton.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_POLAND } from './combatAnatomyGroups/poland.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_RUSSIA } from './combatAnatomyGroups/russia.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_SOVIETHEAVY } from './combatAnatomyGroups/sovietHeavy.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_SWEDEN } from './combatAnatomyGroups/sweden.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_T72 } from './combatAnatomyGroups/t72.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_T80 } from './combatAnatomyGroups/t80.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_T90 } from './combatAnatomyGroups/t90.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_UK } from './combatAnatomyGroups/uk.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_UKRAINE } from './combatAnatomyGroups/ukraine.generated.js';
import { COMBAT_ANATOMY_CALIBRATIONS as CALIBRATIONS_WW2 } from './combatAnatomyGroups/ww2.generated.js';

export const COMBAT_ANATOMY_CALIBRATIONS = Object.freeze(Object.assign({},
  CALIBRATIONS_ABRAMS,
  CALIBRATIONS_AFV,
  CALIBRATIONS_CASEMATE,
  CALIBRATIONS_CHALLENGER,
  CALIBRATIONS_CORE,
  CALIBRATIONS_FRANCECORE,
  CALIBRATIONS_GERMANY,
  CALIBRATIONS_ITALY,
  CALIBRATIONS_JAPAN,
  CALIBRATIONS_KOREA,
  CALIBRATIONS_LEOPARD,
  CALIBRATIONS_MERKAVA,
  CALIBRATIONS_MISC,
  CALIBRATIONS_MODERN2,
  CALIBRATIONS_MODERN3CORE,
  CALIBRATIONS_PATTON,
  CALIBRATIONS_POLAND,
  CALIBRATIONS_RUSSIA,
  CALIBRATIONS_SOVIETHEAVY,
  CALIBRATIONS_SWEDEN,
  CALIBRATIONS_T72,
  CALIBRATIONS_T80,
  CALIBRATIONS_T90,
  CALIBRATIONS_UK,
  CALIBRATIONS_UKRAINE,
  CALIBRATIONS_WW2,
));
