// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "m1a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6143866,
          0.2885127,
          -0.8384999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6143866,
          0.2885127,
          -0.2697999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a1ha": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6250547,
          0.3267926,
          -1.2253641
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001283
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6015121,
          0.3267926,
          -0.1244897
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6053866,
          0.3152727,
          -0.0112999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0009478
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5223865,
          0.3152726,
          -0.1146999
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_tusk": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5151556,
          0.3367727,
          -0.0629999
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5047737,
          0.3375465,
          -2.7511236
        ],
        "quaternion": [
          -0.1590535,
          0.6720668,
          0.1665557,
          0.7037666
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0183177
      }
    ]
  },
  "m1a2_sepv2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5310637,
          0.2894727,
          0.2576501
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5262288,
          0.2902465,
          -2.7072736
        ],
        "quaternion": [
          -0.1590535,
          0.6720668,
          0.1665557,
          0.7037666
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_sepv3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          -1.996,
          1.26586,
          -0.86692
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "m1a2_sepv3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0157843
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6096511,
          0.3025927,
          -0.0112999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0009478
      }
    ]
  },
  "m1a3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          2.0664204,
          1.6059637,
          -3.2360629
        ],
        "quaternion": [
          -0.4743183,
          0.5294026,
          0.4693685,
          0.523878
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "m1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153858
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.2913287,
          0.4703704,
          -0.4332
        ],
        "quaternion": [
          -0.152708,
          0.6904204,
          0.152708,
          0.6904204
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "abramsx": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.4,
        "pos": [
          1.7793983,
          1.2002785,
          2.38
        ],
        "quaternion": [
          -0.0164141,
          0.7069162,
          0.0164141,
          0.7069162
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0126089
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.4,
        "pos": [
          -1.7783026,
          1.2002784,
          2.3800911
        ],
        "quaternion": [
          -0.0162889,
          -0.7015268,
          -0.0165383,
          0.7122649
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0137066
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.683,
          -0.06828,
          -0.82895
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "abramsx",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
