// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "m1a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6143866,
          0.2885127,
          -0.6607499
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6143866,
          0.2885127,
          -0.0485999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a1ha": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6250547,
          0.3267926,
          -1.1059499
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001283
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6015121,
          0.3267926,
          -0.2155499
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a1ha",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6053866,
          0.3152727,
          -0.1598999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.5560996,
          -0.0418473,
          -1.1615999
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "m1a2_tusk": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5677094,
          0.1805127,
          0.1740001
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.4626018,
          0.4930327,
          0.0627001
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_tusk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a2_sepv2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.5310637,
          0.2894727,
          0.0102001
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.3861222,
          0.5195674,
          -2.664326
        ],
        "quaternion": [
          -0.1658869,
          0.7009404,
          0.159751,
          0.6750138
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0018814
      }
    ]
  },
  "m1a2_sepv3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          -0.986,
          0.54676,
          0.3926
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "m1a2_sepv3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.6558902
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          -1.6331938,
          0.3025927,
          -1.9963499
        ],
        "quaternion": [
          -0.114204,
          -0.6978234,
          -0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_sepv3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "m1a3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          2.0664204,
          1.6059637,
          -3.2360629
        ],
        "quaternion": [
          -0.4743183,
          0.5294026,
          0.4693685,
          0.523878
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "m1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153858
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.478377,
          0.4139568,
          -0.4332
        ],
        "quaternion": [
          -0.0529928,
          0.7051183,
          0.0529928,
          0.7051183
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "abramsx": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.4,
        "pos": [
          1.7793983,
          1.2002785,
          2.38
        ],
        "quaternion": [
          -0.0164141,
          0.7069162,
          0.0164141,
          0.7069162
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0126089
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.4,
        "pos": [
          -1.7783026,
          1.2002784,
          2.3800911
        ],
        "quaternion": [
          -0.0162889,
          -0.7015268,
          -0.0165383,
          0.7122649
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0137066
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -0.3990801,
          0.3777009,
          -0.0472464
        ],
        "quaternion": [
          -0.0457209,
          -0.6994863,
          -0.0465168,
          0.7116634
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "abramsx",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.006815
      }
    ]
  },
  "m1a2_legacy": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.421,
          0.19685,
          -0.913281
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_legacy",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.421,
          0.19685,
          -1.2643147
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m1a2_legacy",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
