// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "aft10_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.6176743,
          1.2858613,
          0.441275
        ],
        "quaternion": [
          -0.0466778,
          -0.7011267,
          -0.0472642,
          0.7099356
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "aft10_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.6040027,
          1.2862166,
          1.2453232
        ],
        "quaternion": [
          -0.0679836,
          -0.7024596,
          -0.0682463,
          0.7051746
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "aft10_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
