// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ajax_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.2019136,
          0.5573262,
          -0.0235091
        ],
        "quaternion": [
          -0.2871913,
          -0.6297724,
          -0.2994624,
          0.6566812
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ajax_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.1800634,
          0.5573262,
          0.3188109
        ],
        "quaternion": [
          -0.2871913,
          -0.6297724,
          -0.2994624,
          0.6566812
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ajax_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
