// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ajax_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.7684371,
          1.4515199,
          2.4137631
        ],
        "quaternion": [
          0,
          -0.7603047,
          0,
          0.6495666
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ajax_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.0821153,
          0.5020462,
          -0.0211331
        ],
        "quaternion": [
          -0.2871914,
          -0.6297724,
          -0.2994624,
          0.6566812
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ajax_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006714
      }
    ]
  }
});
