// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "amx10p": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3239468,
          1.3543545,
          -0.4314
        ],
        "quaternion": [
          -0.0445494,
          -0.705702,
          -0.0445494,
          0.705702
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "amx10p",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3239468,
          1.3543545,
          0.2099
        ],
        "quaternion": [
          -0.0445494,
          -0.705702,
          -0.0445494,
          0.705702
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "amx10p",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "amx10p_25": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.726,
          1.1748,
          0.1516
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hullExternalArmor",
        "anchorProfile": "amx10p_25",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.726,
          1.1748,
          0.7929
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hullExternalArmor",
        "anchorProfile": "amx10p_25",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
