// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "bmp3m_dragun125_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.5825708,
          1.8367006,
          0.2158564
        ],
        "quaternion": [
          -0.0618799,
          -0.7081569,
          -0.0612256,
          0.7006683
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bmp3m_dragun125_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.5919245,
          1.8367006,
          1.0899285
        ],
        "quaternion": [
          -0.0618182,
          -0.70745,
          -0.0612879,
          0.7013821
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bmp3m_dragun125_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0000323
      }
    ]
  }
});
