// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "borsuk": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.296553,
          1.6993319,
          1.4443647
        ],
        "quaternion": [
          -0.0608121,
          -0.7018441,
          -0.0612658,
          0.7070808
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "borsuk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2189828
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -0.9555,
          0.95013,
          2.1709801
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "borsuk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.567
      }
    ]
  }
});
