// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "challenger1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0140989,
          0.2897412,
          -1.7454224
        ],
        "quaternion": [
          0,
          -0.7896496,
          0,
          0.6135581
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4141323,
          0.2897412,
          0.2373434
        ],
        "quaternion": [
          0,
          -0.7948778,
          0,
          0.6067695
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0026609
      }
    ]
  }
});
