// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "cv90_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.4537891,
          1.4881984,
          2.0918017
        ],
        "quaternion": [
          -0.2007928,
          -0.6133501,
          -0.2376548,
          0.7259505
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "cv90_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.095776
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.0587905,
          0.4436397,
          0.5863211
        ],
        "quaternion": [
          0.0849669,
          -0.7125252,
          0.0824696,
          0.6915831
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cv90_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
