// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "dardo": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3797639,
          1.3596124,
          -0.5122
        ],
        "quaternion": [
          -0.0658376,
          -0.7040351,
          -0.0658376,
          0.7040351
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "dardo",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3797639,
          1.3596124,
          0.2127
        ],
        "quaternion": [
          -0.0658376,
          -0.7040351,
          -0.0658376,
          0.7040351
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "dardo",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
