// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "fv510_milan_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -0.9801135,
          0.789607,
          0.3436819
        ],
        "quaternion": [
          0.0308475,
          -0.7064336,
          0.0308475,
          0.7064336
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510_milan_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 1.1476131
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.1583764,
          1.5901505,
          2.2586553
        ],
        "quaternion": [
          -0.2869716,
          -0.5631101,
          -0.3518732,
          0.6904633
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510_milan_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0130433
      }
    ]
  }
});
