// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "carro45t": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.4005323,
          0.3828778,
          -0.2500797
        ],
        "quaternion": [
          -0.1761957,
          -0.6896349,
          -0.1738707,
          0.6805349
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3072905,
          0.452154,
          0.1593545
        ],
        "quaternion": [
          -0.2060735,
          0.6668263,
          0.2114506,
          0.6842259
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "carro45t",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ariete": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.3122426,
          0.3035107,
          -0.7501913
        ],
        "quaternion": [
          -0.011709,
          0.7181948,
          0.0113414,
          0.6956511
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000078
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.3125179,
          0.3035183,
          -0.7501913
        ],
        "quaternion": [
          -0.0113405,
          -0.7182011,
          -0.0109845,
          0.6956565
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000077
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.2754479,
          0.4341846,
          0.2325619
        ],
        "quaternion": [
          -0.0104014,
          -0.6730988,
          -0.0114258,
          0.7393911
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001301
      }
    ]
  },
  "ariete_c1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.407565,
          0.3799413,
          -0.5332799
        ],
        "quaternion": [
          -0.0065578,
          0.7070764,
          0.0065578,
          0.7070764
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3645,
          0.462858,
          -1.3499199
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ariete_c2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4078217,
          0.3661033,
          -0.6863999
        ],
        "quaternion": [
          -0.0065578,
          -0.7070764,
          -0.0065578,
          0.7070764
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.2866496,
          0.3661158,
          1.5086582
        ],
        "quaternion": [
          -0.007101,
          -0.6868585,
          -0.0075131,
          0.7267176
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0173754
      }
    ]
  }
});
