// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "k21_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3667836,
          1.6603755,
          -0.022
        ],
        "quaternion": [
          -0.0734381,
          -0.7113649,
          -0.0717776,
          0.6952804
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "k21_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.104438
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.3777733,
          1.6603756,
          1.0619104
        ],
        "quaternion": [
          -0.0719093,
          -0.6965562,
          -0.0733092,
          0.7101157
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "k21_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1042291
      }
    ]
  }
});
