// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "k21_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.4218251,
          1.84469,
          0.3505401
        ],
        "quaternion": [
          -0.0808466,
          -0.783127,
          -0.0633169,
          0.6133244
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "k21_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.4157229,
          1.8493504,
          -0.5506194
        ],
        "quaternion": [
          -0.4275606,
          -0.5288094,
          -0.4609745,
          0.570136
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "k21_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
