// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "kf41_lynx_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.4144167,
          0.4179478,
          0.1152255
        ],
        "quaternion": [
          -0.1417627,
          -0.6827255,
          -0.1457277,
          0.701821
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf41_lynx_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0087685
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.3909405,
          0.4179162,
          0.6745271
        ],
        "quaternion": [
          -0.1314026,
          -0.6328316,
          -0.1551341,
          0.7471218
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf41_lynx_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0016431
      }
    ]
  }
});
