// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "kurganets25_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.4369098,
          1.8636971,
          -0.1186307
        ],
        "quaternion": [
          -0.0278091,
          -0.7055951,
          -0.027885,
          0.70752
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "kurganets25_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.4164334
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.4378371,
          1.8636971,
          -0.4467248
        ],
        "quaternion": [
          -0.0278072,
          -0.7055465,
          -0.0278869,
          0.7075686
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "kurganets25_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.4156608
      }
    ]
  }
});
