// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "leclerc_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.5120541,
          0.5768668,
          -1.6599865
        ],
        "quaternion": [
          -0.2497872,
          0.6550943,
          0.2540488,
          0.6662709
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0070585
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.4300629,
          0.5778153,
          -0.8163079
        ],
        "quaternion": [
          -0.3428673,
          0.6487529,
          0.3174483,
          0.6006565
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0045967
      }
    ]
  }
});
