// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "lrmv_lynx": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.2660779,
          0.4975959,
          -0.2999888
        ],
        "quaternion": [
          -0.1212468,
          -0.7078338,
          -0.1174906,
          0.6859056
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "lrmv_lynx",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0066328
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.2671115,
          0.4981207,
          0.0643
        ],
        "quaternion": [
          -0.1520963,
          -0.6905554,
          -0.1520963,
          0.6905554
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "lrmv_lynx",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
