// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "marder2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.6885921,
          1.4774237,
          -0.0731027
        ],
        "quaternion": [
          -0.0725071,
          -0.7035413,
          -0.0724741,
          0.7032211
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0025087
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.5938761,
          1.8544744,
          -0.0730611
        ],
        "quaternion": [
          -0.0872738,
          -0.6993839,
          -0.0878422,
          0.7039384
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
