// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "marder2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.6767654,
          1.5874897,
          -1.2762
        ],
        "quaternion": [
          -0.0824527,
          -0.7022831,
          -0.0824527,
          0.7022831
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.6753115,
          1.5877483,
          -0.0985613
        ],
        "quaternion": [
          -0.0977604,
          -0.698014,
          -0.0983918,
          0.7025229
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0020791
      }
    ]
  }
});
