// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, unknown>> = Object.freeze({
  "type59": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.6051776,
          0.2735828,
          -0.2266496
        ],
        "quaternion": [
          -0.0941064,
          0.7008167,
          0.0941064,
          0.7008167
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0132292
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3164141,
          0.439827,
          -0.9645273
        ],
        "quaternion": [
          -0.2570755,
          0.8392037,
          0.1403618,
          0.4582007
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153825
      }
    ]
  },
  "ztz85_iii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.957133,
          0.27,
          0.6821886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          1.0668237,
          0.27,
          0.4021886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          -1.0080608,
          0.27,
          0.5521886
        ],
        "quaternion": [
          0,
          -0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "type99a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.5339248,
          0.5376,
          -0.677167
        ],
        "quaternion": [
          0,
          -0.7284099,
          0,
          0.6851416
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.5339248,
          0.5376,
          -0.677167
        ],
        "quaternion": [
          0,
          0.7284099,
          0,
          0.6851416
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5067275,
          0.581935,
          -1.1210109
        ],
        "quaternion": [
          0,
          -0.7284099,
          0,
          0.6851416
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type99a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ztz99a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0695146,
          0.5245329,
          0.4218412
        ],
        "quaternion": [
          -0.2605608,
          -0.5278972,
          -0.3577797,
          0.724863
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          1.5105482,
          0.3,
          -0.8109965
        ],
        "quaternion": [
          0,
          0.7635712,
          0,
          0.6457236
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0055313
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.5105482,
          0.3,
          -0.8109965
        ],
        "quaternion": [
          0,
          -0.7635712,
          0,
          0.6457236
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.008297
      }
    ]
  },
  "vt4a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.5975892,
          0.3936,
          -0.7203594
        ],
        "quaternion": [
          0,
          -0.727974,
          0,
          0.6856047
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019703
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.5975892,
          0.3936,
          -0.7203594
        ],
        "quaternion": [
          0,
          0.727974,
          0,
          0.6856047
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0016744
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5686812,
          0.387547,
          -1.2021594
        ],
        "quaternion": [
          0,
          -0.727974,
          0,
          0.6856047
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "vt4a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "mbt70": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          1.6490909,
          0.4414671,
          -1.7205311
        ],
        "quaternion": [
          -0.091251,
          0.7320722,
          0.0835018,
          0.6699037
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1273932
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          -1.6490909,
          0.4414671,
          -1.7205311
        ],
        "quaternion": [
          -0.091251,
          -0.7320722,
          -0.0835018,
          0.6699037
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1273932
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.6831559,
          0.3452771,
          -1.1556519
        ],
        "quaternion": [
          -0.0735859,
          0.6823352,
          0.0779857,
          0.7231335
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "mbt70",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0014162
      }
    ]
  },
  "t14": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          1.866,
          1.22,
          3.05
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.051
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          -1.866,
          1.22,
          3.05
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.051
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.026,
          0.41274,
          -0.7383201
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t14",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
