// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "type59": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.6051776,
          0.2735828,
          -0.2266496
        ],
        "quaternion": [
          -0.0941064,
          0.7008167,
          0.0941064,
          0.7008167
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0132292
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3164141,
          0.439827,
          -0.9645273
        ],
        "quaternion": [
          -0.2570755,
          0.8392037,
          0.1403618,
          0.4582007
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153825
      }
    ]
  },
  "ztz85_iii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.957133,
          0.27,
          0.6821886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          1.0668237,
          0.27,
          0.4021886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          -1.0080608,
          0.27,
          0.5521886
        ],
        "quaternion": [
          0,
          -0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "type99a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.5339248,
          0.3936,
          -0.677167
        ],
        "quaternion": [
          0,
          -0.7284099,
          0,
          0.6851416
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0020551
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.5339248,
          0.3936,
          -0.677167
        ],
        "quaternion": [
          0,
          0.7284099,
          0,
          0.6851416
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0017451
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4693431,
          0.5394986,
          -1.1671795
        ],
        "quaternion": [
          -0.2165647,
          -0.678516,
          -0.2134323,
          0.668702
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type99a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.010799
      }
    ]
  },
  "ztz99a2_prototype": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0695146,
          0.5245329,
          0.4218412
        ],
        "quaternion": [
          -0.2605608,
          -0.5278972,
          -0.3577797,
          0.724863
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0089319
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          1.5105482,
          0.3,
          -0.8109965
        ],
        "quaternion": [
          0,
          0.7635712,
          0,
          0.6457236
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0055313
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.5105482,
          0.3,
          -0.8109965
        ],
        "quaternion": [
          0,
          -0.7635712,
          0,
          0.6457236
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.008297
      }
    ]
  },
  "ztz99a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5675919,
          0.3514768,
          0.1395492
        ],
        "quaternion": [
          -0.0374136,
          -0.7404628,
          -0.0338634,
          0.6702003
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz99a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.5753591,
          0.3514768,
          0.216931
        ],
        "quaternion": [
          -0.0374136,
          0.7404628,
          0.0338634,
          0.6702003
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz99a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "vt4a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.5975892,
          0.3936,
          -0.7203594
        ],
        "quaternion": [
          0,
          -0.727974,
          0,
          0.6856047
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019703
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.5975892,
          0.3936,
          -0.7203594
        ],
        "quaternion": [
          0,
          0.727974,
          0,
          0.6856047
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0016744
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5340185,
          0.5395975,
          -1.0236158
        ],
        "quaternion": [
          -0.2233962,
          -0.6760827,
          -0.2202931,
          0.6666913
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "vt4a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "type100": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -0.8146492,
          0.5932931,
          -0.3430799
        ],
        "quaternion": [
          -0.2340572,
          -0.667246,
          -0.2340572,
          0.667246
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type100",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -0.8146492,
          0.5932931,
          -0.0032399
        ],
        "quaternion": [
          -0.2340572,
          -0.667246,
          -0.2340572,
          0.667246
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type100",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ztz100_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.506,
          0.5921794,
          -0.925
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz100_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.506,
          0.5921794,
          -0.5125
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz100_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ztz100_prototype": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.606,
          0.2726,
          -1.0728
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz100_prototype",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0008696
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.606,
          0.2726,
          -0.7384
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ztz100_prototype",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "mbt70": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          1.6490909,
          0.4414671,
          -1.7205311
        ],
        "quaternion": [
          -0.091251,
          0.7320722,
          0.0835018,
          0.6699037
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1273932
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          -1.6510018,
          0.44146,
          -1.7204957
        ],
        "quaternion": [
          -0.0905121,
          -0.7301469,
          -0.0833193,
          0.6721242
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1251958
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.6831559,
          0.3452771,
          -1.1556519
        ],
        "quaternion": [
          -0.0735859,
          0.6823352,
          0.0779857,
          0.7231335
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "mbt70",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0014162
      }
    ]
  },
  "t14": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.5338953,
          0.4190754,
          -0.4057561
        ],
        "quaternion": [
          -0.1537401,
          0.6814535,
          0.1574705,
          0.6979886
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t14",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0040082
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.296,
          0.4165,
          -1.7358
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t14",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "object695_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.797,
          1.26684,
          0.675
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hullExternalArmor",
        "anchorProfile": "object695_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.797,
          1.26684,
          1.3754249
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hullExternalArmor",
        "anchorProfile": "object695_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
