// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ua_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9204237,
          0.6153047,
          -1.0227846
        ],
        "quaternion": [
          0.4760513,
          0.7887233,
          0.2009928,
          -0.3330055
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0898401
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5252898,
          0.5852267,
          -1.202246
        ],
        "quaternion": [
          0.5732364,
          0.6520942,
          0.3275808,
          -0.3726447
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2290736
      }
    ]
  },
  "ua_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.7875327,
          0.6614544,
          -1.1191739
        ],
        "quaternion": [
          0.5079433,
          0.6998748,
          0.2949574,
          -0.4064099
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.01371
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.7875327,
          0.6614544,
          -1.1191739
        ],
        "quaternion": [
          -0.5079433,
          0.6998748,
          0.2949574,
          0.4064099
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.01371
      }
    ]
  },
  "ua_t72b3m_hetman_ii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1763344,
          0.6765329,
          -2.3001262
        ],
        "quaternion": [
          -0.3195058,
          -0.6708888,
          -0.2877358,
          0.6041791
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_hetman_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0163841
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2375719,
          0.6775379,
          -1.5876065
        ],
        "quaternion": [
          -0.4092496,
          -0.5842857,
          -0.4020488,
          0.574005
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_hetman_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0002221
      }
    ]
  },
  "ua_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.7768634,
          0.528126,
          -1.1173417
        ],
        "quaternion": [
          0.4397556,
          0.8377094,
          0.1505102,
          -0.2867135
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.007925
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2124485,
          0.529597,
          -0.3404
        ],
        "quaternion": [
          -0.2906848,
          0.6445947,
          0.2906848,
          0.6445947
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0106041
      }
    ]
  },
  "pl_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6369136,
          0.6279173,
          -1.1751315
        ],
        "quaternion": [
          0.5589461,
          0.6881415,
          0.2916875,
          -0.3591085
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0135814
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1095157,
          0.6615592,
          -0.7131702
        ],
        "quaternion": [
          -0.3617404,
          -0.6519214,
          -0.3233526,
          0.5827396
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0327815
      }
    ]
  },
  "pl_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6453624,
          0.6624648,
          -1.229435
        ],
        "quaternion": [
          0.5374328,
          0.6873269,
          0.3009743,
          -0.3849183
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0076895
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1829367,
          0.6978799,
          -0.4352
        ],
        "quaternion": [
          -0.3732507,
          -0.6005697,
          -0.3732507,
          0.6005697
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0860165
      }
    ]
  },
  "pl_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5075577,
          0.5760366,
          -1.1202997
        ],
        "quaternion": [
          0.6089483,
          0.6739085,
          0.2804894,
          -0.3104109
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0106284
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0906884,
          0.6077912,
          -0.6631135
        ],
        "quaternion": [
          -0.3847828,
          -0.6348735,
          -0.3472608,
          0.572964
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0173316
      }
    ]
  },
  "pl_t72b3_zubr_ii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3087509,
          0.7510447,
          -1.9273009
        ],
        "quaternion": [
          -0.3239754,
          -0.691701,
          -0.2737658,
          0.5845014
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_zubr_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0446925
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2983644,
          0.7510447,
          -1.9666009
        ],
        "quaternion": [
          -0.3239754,
          0.691701,
          0.2737658,
          0.5845014
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_zubr_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0368309
      }
    ]
  },
  "cn_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.044,
          0.83605,
          -1.6799999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 5,
        "visibilityRatio": 0.5555556,
        "maximumSurfaceErrorM": 1.121006
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.6312881,
          0.5937182,
          -1.1819736
        ],
        "quaternion": [
          -0.5633979,
          0.668621,
          0.3127207,
          0.371126
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0317807
      }
    ]
  },
  "cn_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8934478,
          0.6883614,
          -1.0768389
        ],
        "quaternion": [
          0.5296754,
          0.6995336,
          0.2895655,
          -0.3824244
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.1015821
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.8934478,
          0.6883614,
          -1.0768389
        ],
        "quaternion": [
          -0.5296754,
          0.6995336,
          0.2895655,
          0.3824244
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.1015821
      }
    ]
  },
  "cn_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6050405,
          0.5848778,
          -1.1340628
        ],
        "quaternion": [
          0.5842529,
          0.674946,
          0.2949506,
          -0.3407355
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.1828364
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1464317,
          0.6170033,
          -0.2635
        ],
        "quaternion": [
          -0.387818,
          -0.5912674,
          -0.387818,
          0.5912674
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0209233
      }
    ]
  },
  "ru_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.6394011,
          0.6109055,
          -1.1977314
        ],
        "quaternion": [
          -0.5487231,
          0.6781205,
          0.3075574,
          0.3800842
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0202208
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2112,
        "pos": [
          0.9013987,
          0.6426577,
          -1.045456
        ],
        "quaternion": [
          -0.4852646,
          0.7654064,
          0.2263328,
          0.3569941
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 5,
        "visibilityRatio": 0.5555556,
        "maximumSurfaceErrorM": 0.1753673
      }
    ]
  },
  "ru_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6281084,
          0.6625835,
          -1.2566958
        ],
        "quaternion": [
          0.5260817,
          0.6815844,
          0.3107654,
          -0.4026235
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2135127
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.8310586,
          0.6974314,
          -1.0978416
        ],
        "quaternion": [
          -0.5130352,
          0.7001896,
          0.2934596,
          0.4005132
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.194953
      }
    ]
  },
  "ru_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5402675,
          0.5765065,
          -1.1672566
        ],
        "quaternion": [
          0.5845894,
          0.6554668,
          0.3182526,
          -0.3568386
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0128898
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.5402675,
          0.5765065,
          -1.1672566
        ],
        "quaternion": [
          -0.5845894,
          0.6554668,
          0.3182526,
          0.3568386
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0128898
      }
    ]
  }
});
