// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ua_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9179474,
          0.6152677,
          -1.0228271
        ],
        "quaternion": [
          0.4770439,
          0.7903679,
          0.1986253,
          -0.3290831
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0138451
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5203358,
          0.5852468,
          -1.2022113
        ],
        "quaternion": [
          0.5721378,
          0.6508445,
          0.3294956,
          -0.374823
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2277311
      }
    ]
  },
  "ua_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0672156,
          0.6616185,
          -0.7681415
        ],
        "quaternion": [
          -0.3668642,
          -0.647203,
          -0.3295274,
          0.5813353
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0283463
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.107188,
          0.6619586,
          0.0888313
        ],
        "quaternion": [
          -0.3700284,
          -0.571961,
          -0.3976543,
          0.614663
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0169835
      }
    ]
  },
  "ua_t72b3m_hetman_ii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2944687,
          0.47975,
          -1.8554124
        ],
        "quaternion": [
          0,
          -0.7589655,
          0,
          0.6511309
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_hetman_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2375719,
          0.6775379,
          -1.5876065
        ],
        "quaternion": [
          -0.4092496,
          -0.5842857,
          -0.4020488,
          0.574005
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_hetman_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0002221
      }
    ]
  },
  "ua_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1334805,
          0.5288837,
          -0.8278542
        ],
        "quaternion": [
          -0.2669186,
          -0.7302568,
          -0.2158914,
          0.5906526
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0103211
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.081882,
          0.6259462,
          -0.512
        ],
        "quaternion": [
          -0.3809136,
          -0.5957389,
          -0.3809136,
          0.5957389
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0129045
      }
    ]
  },
  "pl_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6302408,
          0.6279524,
          -1.1750795
        ],
        "quaternion": [
          0.5574053,
          0.6862446,
          0.2946213,
          -0.3627203
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.013033
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1112758,
          0.661739,
          -0.7131077
        ],
        "quaternion": [
          -0.378646,
          -0.638179,
          -0.3420519,
          0.5765026
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0107561
      }
    ]
  },
  "pl_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.640441,
          0.6626782,
          -1.2291722
        ],
        "quaternion": [
          0.5493275,
          0.6615078,
          0.3261606,
          -0.3927671
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0140039
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1829367,
          0.6978799,
          -0.4352
        ],
        "quaternion": [
          -0.3732507,
          -0.6005697,
          -0.3732507,
          0.6005697
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0668363
      }
    ]
  },
  "pl_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5011683,
          0.5760699,
          -1.1202602
        ],
        "quaternion": [
          0.6077341,
          0.6725648,
          0.2831106,
          -0.3133117
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0103602
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0931984,
          0.6077961,
          -0.6630575
        ],
        "quaternion": [
          -0.3831497,
          -0.6321791,
          -0.3490618,
          0.5759355
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0049995
      }
    ]
  },
  "pl_t72b3_zubr_ii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3087509,
          0.7510447,
          -1.9273009
        ],
        "quaternion": [
          -0.3239754,
          -0.691701,
          -0.2737658,
          0.5845014
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_zubr_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0446925
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2983644,
          0.7510447,
          -1.9666009
        ],
        "quaternion": [
          -0.3239754,
          0.691701,
          0.2737658,
          0.5845014
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_zubr_ii",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0368309
      }
    ]
  },
  "cn_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.044,
          1.4545,
          -2.8223999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.937
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9028958,
          0.6249785,
          -1.0484945
        ],
        "quaternion": [
          0.5239688,
          0.7302981,
          0.2555172,
          -0.3561353
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.279738
      }
    ]
  },
  "cn_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6635828,
          0.6542533,
          -1.214209
        ],
        "quaternion": [
          0.5568765,
          0.6382023,
          0.349502,
          -0.4005431
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0214689
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2112,
        "pos": [
          0.8973941,
          0.6886775,
          -1.0764671
        ],
        "quaternion": [
          -0.5479944,
          0.6622894,
          0.3257305,
          0.393668
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0141052
      }
    ]
  },
  "cn_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6002746,
          0.5851125,
          -1.1337677
        ],
        "quaternion": [
          0.593326,
          0.6482812,
          0.3221637,
          -0.3520033
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.203559
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1464316,
          0.6170033,
          -0.442
        ],
        "quaternion": [
          -0.3878176,
          -0.5912677,
          -0.3878176,
          0.5912677
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0149306
      }
    ]
  },
  "ru_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6334871,
          0.6109315,
          -1.1976874
        ],
        "quaternion": [
          0.5474002,
          0.6764856,
          0.3099059,
          -0.3829865
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0087984
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.5519933,
          0.6109796,
          -1.2282524
        ],
        "quaternion": [
          -0.5555606,
          0.667622,
          0.3170179,
          0.3809631
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0109843
      }
    ]
  },
  "ru_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6236019,
          0.6626046,
          -1.2566559
        ],
        "quaternion": [
          0.5249006,
          0.6800542,
          0.3127562,
          -0.4052027
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2121229
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.832123,
          0.6972514,
          -1.0980101
        ],
        "quaternion": [
          -0.5000616,
          0.7193411,
          0.2752198,
          0.395905
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.2078687
      }
    ]
  },
  "ru_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5345983,
          0.5765288,
          -1.1672215
        ],
        "quaternion": [
          0.5834819,
          0.654225,
          0.3202786,
          -0.3591102
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0123862
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.5452674,
          0.5762267,
          -1.1675863
        ],
        "quaternion": [
          -0.5703617,
          0.6881473,
          0.2861972,
          0.3452999
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0146165
      }
    ]
  }
});
