// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ua_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8802264,
          0.4899178,
          -1.9127507
        ],
        "quaternion": [
          -0.0984614,
          -0.5869666,
          -0.1329437,
          0.7925286
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0098292
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.7989006,
          0.5384082,
          -1.4950062
        ],
        "quaternion": [
          -0.3025064,
          -0.7163576,
          -0.244595,
          0.5792193
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0166863
      }
    ]
  },
  "ua_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9019182,
          0.4900573,
          -2.1281068
        ],
        "quaternion": [
          -0.1084987,
          -0.61002,
          -0.1374499,
          0.7727943
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0008043
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.6637009,
          0.6541731,
          -1.4783649
        ],
        "quaternion": [
          -0.3220697,
          -0.6843555,
          -0.2785547,
          0.5918918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0156388
      }
    ]
  },
  "ua_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9293865,
          0.4897662,
          -1.9489419
        ],
        "quaternion": [
          -0.0883129,
          -0.5626062,
          -0.1274685,
          0.812051
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9151346,
          0.5922377,
          -0.9657563
        ],
        "quaternion": [
          -0.3114513,
          -0.7298544,
          -0.2388417,
          0.5597011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "pl_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8231399,
          0.4901553,
          -1.9133742
        ],
        "quaternion": [
          -0.1160437,
          -0.6266664,
          -0.1403112,
          0.7577175
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.011107
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.7989006,
          0.5384082,
          -1.4950062
        ],
        "quaternion": [
          -0.3025064,
          -0.7163576,
          -0.244595,
          0.5792193
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0166863
      }
    ]
  },
  "pl_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8368821,
          0.4902371,
          -2.1286102
        ],
        "quaternion": [
          -0.122728,
          -0.6409231,
          -0.1425058,
          0.7442093
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0002516
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8515618,
          0.388036,
          -1.4792575
        ],
        "quaternion": [
          0,
          -0.8040241,
          0,
          0.5945967
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "pl_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8543619,
          0.4900657,
          -1.9496789
        ],
        "quaternion": [
          -0.1091244,
          -0.6114227,
          -0.1377036,
          0.7715516
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8296581,
          0.388036,
          -1.5507574
        ],
        "quaternion": [
          0,
          -0.8040241,
          0,
          0.5945967
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pl_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "cn_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.937252,
          0.4896676,
          -1.9121724
        ],
        "quaternion": [
          -0.0820629,
          -0.5470798,
          -0.1235762,
          0.8238315
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0082734
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9105839,
          0.6538393,
          -0.8064711
        ],
        "quaternion": [
          -0.304464,
          -0.7134804,
          -0.2476871,
          0.5804295
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0024694
      }
    ]
  },
  "cn_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9669128,
          0.4898658,
          -2.1276245
        ],
        "quaternion": [
          -0.0948981,
          -0.5785336,
          -0.1311331,
          0.7994357
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0010638
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8573,
          0.6537817,
          -0.9493063
        ],
        "quaternion": [
          -0.3114513,
          -0.7298544,
          -0.2388417,
          0.5597011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "cn_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0043319,
          0.4894573,
          -1.9482859
        ],
        "quaternion": [
          -0.0694826,
          -0.5146191,
          -0.1143483,
          0.8469143
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8509147,
          0.6537817,
          -0.9657563
        ],
        "quaternion": [
          -0.3114513,
          -0.7298544,
          -0.2388417,
          0.5597011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cn_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ru_t80u_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9471384,
          0.5922377,
          -0.8833063
        ],
        "quaternion": [
          -0.3114513,
          -0.7298544,
          -0.2388417,
          0.5597011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0007235
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.7989006,
          0.5384082,
          -1.4950062
        ],
        "quaternion": [
          -0.3025064,
          -0.7163576,
          -0.244595,
          0.5792193
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t80u_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.047358
      }
    ]
  },
  "ru_t72b3m_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8898847,
          0.5922377,
          -1.0308063
        ],
        "quaternion": [
          -0.3114513,
          -0.7298544,
          -0.2388417,
          0.5597011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.2584492
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8032143,
          0.5387781,
          -1.4783649
        ],
        "quaternion": [
          -0.3220697,
          -0.6843555,
          -0.2785547,
          0.5918918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3m_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "ru_t72b3_modern": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9138285,
          0.5383613,
          -1.1120818
        ],
        "quaternion": [
          -0.3140282,
          -0.7358931,
          -0.2354433,
          0.5517373
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0089208
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9075837,
          0.6846113,
          -0.709571
        ],
        "quaternion": [
          -0.304464,
          -0.7134804,
          -0.2476871,
          0.5804295
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ru_t72b3_modern",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.1593272
      }
    ]
  }
});
