// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72m1_jaguar": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.2127766,
          0.3681337,
          -0.1002055
        ],
        "quaternion": [
          -0.1984571,
          -0.6962113,
          -0.189113,
          0.6634311
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72m1_jaguar",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0139667
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.0714702,
          0.4788329,
          0.1854393
        ],
        "quaternion": [
          -0.3204226,
          -0.5732792,
          -0.3679236,
          0.6582648
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72m1_jaguar",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0064888
      }
    ]
  },
  "pt91_twardy": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          1.636,
          1.222,
          -2.8586
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pt91_twardy",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4519581,
          0.4329621,
          -0.37297
        ],
        "quaternion": [
          0,
          -0.7548321,
          0,
          0.655918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pt91_twardy",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0228431
      }
    ]
  },
  "pl01": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.39495,
          -0.10195
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pl01",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "pl01_105": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.8203795,
          1.0162728,
          0.31475
        ],
        "quaternion": [
          0.1028693,
          -0.6995841,
          0.1028693,
          0.6995841
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pl01_105",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.2421605
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.7874718,
          1.9208818,
          1.5651284
        ],
        "quaternion": [
          -0.3653318,
          -0.5859485,
          -0.3826931,
          0.6137939
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pl01_105",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.046188
      }
    ]
  }
});
