// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72m1_jaguar": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.2127766,
          0.3681337,
          -0.1002055
        ],
        "quaternion": [
          -0.1984571,
          -0.6962113,
          -0.189113,
          0.6634311
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72m1_jaguar",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0139667
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.0714702,
          0.4788329,
          0.1854393
        ],
        "quaternion": [
          -0.3204226,
          -0.5732792,
          -0.3679236,
          0.6582648
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72m1_jaguar",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0064888
      }
    ]
  },
  "pt91_twardy": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3662963,
          0.42,
          -0.9808373
        ],
        "quaternion": [
          0,
          -0.7548321,
          0,
          0.655918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3662963,
          0.42,
          -0.9808373
        ],
        "quaternion": [
          0,
          0.7548321,
          0,
          0.655918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.4276893,
          0.4329621,
          -0.5451846
        ],
        "quaternion": [
          0,
          0.7548321,
          0,
          0.655918
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pt91_twardy",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "pl01": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.39495,
          -0.10195
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pl01",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "pl01_105": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          1.906,
          1.62,
          -0.6
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.906,
          1.39495,
          -0.10195
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "pl01_105",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
