// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "spz_puma_s1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.6738659,
          1.8371068,
          1.1042414
        ],
        "quaternion": [
          -0.0818453,
          -0.687885,
          -0.085207,
          0.7161392
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "spz_puma_s1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0656722
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.6799731,
          1.8371079,
          0.7359803
        ],
        "quaternion": [
          -0.0836804,
          -0.7033082,
          -0.0834056,
          0.7009984
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "spz_puma_s1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0912164
      }
    ]
  }
});
