// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t62mv1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          0.6312795,
          0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          -0.6312796,
          -0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4121064,
          0.5192377,
          -0.5605697
        ],
        "quaternion": [
          -0.2117147,
          -0.674668,
          -0.2117147,
          0.674668
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t64bv1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2919222,
          0.2733313,
          -0.0748895
        ],
        "quaternion": [
          -0.0264752,
          0.7544952,
          0.0229968,
          0.655368
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t64bv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0015451
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.0243517,
          0.5631409,
          0.2114041
        ],
        "quaternion": [
          -0.388529,
          0.5217011,
          0.4536578,
          0.6091533
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t64bv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0091702
      }
    ]
  }
});
