// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "sabra_mk2_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.003832,
          0.8025901,
          -0.1555199
        ],
        "quaternion": [
          0.0836688,
          -0.7021393,
          0.0836688,
          0.7021393
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "sabra_mk2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.2,
        "pos": [
          -1.0133363,
          0.802454,
          1.6221357
        ],
        "quaternion": [
          0.092063,
          -0.7025372,
          0.0916893,
          0.6996849
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "sabra_mk2_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
