// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "type96_72_long": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.3416269,
          0.5145587,
          -0.5799393
        ],
        "quaternion": [
          -0.2805563,
          -0.6515831,
          -0.2787261,
          0.6473326
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_72_long",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.374941,
          0.4342262,
          0.056033
        ],
        "quaternion": [
          -0.2620045,
          -0.6084971,
          -0.2962325,
          0.6879907
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_72_long",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "type96_80_feng": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.3427612,
          0.5145587,
          -0.4608393
        ],
        "quaternion": [
          -0.2805563,
          -0.6515831,
          -0.2787261,
          0.6473326
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_80_feng",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.1108625,
          0.3758254,
          1.0500801
        ],
        "quaternion": [
          -0.2405869,
          -0.5021048,
          -0.3589422,
          0.7491123
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_80_feng",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "type96_72m_lei": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.3421593,
          0.5145587,
          -0.5240393
        ],
        "quaternion": [
          -0.2805563,
          -0.6515831,
          -0.2787261,
          0.6473326
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_72m_lei",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.2016194,
          0.5148146,
          0.4317709
        ],
        "quaternion": [
          -0.2797368,
          -0.5838107,
          -0.3293461,
          0.6873453
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type96_72m_lei",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
