// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t62mv1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2371774,
          0.1826354,
          -0.1452207
        ],
        "quaternion": [
          0,
          -0.7783809,
          0,
          0.6277924
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0091525
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5533869,
          0.2357272,
          -1.1200208
        ],
        "quaternion": [
          0.0520669,
          0.9317555,
          0.0200485,
          -0.3587741
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.00321
      }
    ]
  }
});
