// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t62mv1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          0.6312795,
          0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          -0.6312796,
          -0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.468217,
          0.2353507,
          -0.6514241
        ],
        "quaternion": [
          -0.0204028,
          -0.7068124,
          -0.0204028,
          0.7068124
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0135826
      }
    ]
  }
});
