// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72b3m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.1056144,
          0.5846488,
          0.150731
        ],
        "quaternion": [
          -0.3763421,
          -0.5533825,
          -0.4178605,
          0.6144323
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b3m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0028078
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -0.8839659,
          0.5848326,
          0.4594414
        ],
        "quaternion": [
          -0.3956977,
          -0.4721442,
          -0.5059778,
          0.6037298
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b3m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.001047
      }
    ]
  },
  "t72bu": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.0919942,
          0.5694521,
          0.4864573
        ],
        "quaternion": [
          -0.3697701,
          0.498782,
          0.4668402,
          0.6297196
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72bu",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0030342
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3752791,
          0.2117483,
          0.185459
        ],
        "quaternion": [
          0,
          0.7514662,
          0,
          0.6597716
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72bu",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0066227
      }
    ]
  }
});
