// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72_rys": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.954935,
          0.239137,
          -0.9505008
        ],
        "quaternion": [
          0.09813,
          0.8772234,
          0.0522444,
          -0.4670332
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72_rys",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0133361
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3648941,
          0.3367604,
          0.0127697
        ],
        "quaternion": [
          -0.0887433,
          -0.7473482,
          -0.0776451,
          0.6538857
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72_rys",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0068396
      }
    ]
  }
});
