// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "pt91m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.1733253,
          0.3375038,
          -0.3872062
        ],
        "quaternion": [
          0,
          -0.8618601,
          0,
          0.5071461
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pt91m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0138468
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.2854541,
          0.388752,
          -0.0874858
        ],
        "quaternion": [
          -0.0688758,
          -0.8156967,
          -0.0483263,
          0.5723283
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pt91m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0003548
      }
    ]
  },
  "t90": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.0847392,
          0.4191534,
          -1.461763
        ],
        "quaternion": [
          -0.0676666,
          -0.7611755,
          -0.0571142,
          0.6424726
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4701368,
          0.4184953,
          0.3334234
        ],
        "quaternion": [
          -0.0211688,
          -0.6511015,
          -0.0246539,
          0.7582948
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0062935
      }
    ]
  },
  "t90a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.6185539,
          0.10675,
          -1.5836288
        ],
        "quaternion": [
          0,
          0.7176335,
          0,
          0.6964209
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0077881
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.2155189,
          0.4222885,
          0.0083077
        ],
        "quaternion": [
          -0.2304606,
          0.7025491,
          0.2098583,
          0.6397438
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t90a_vladimir": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4514915,
          0.247275,
          -0.7259604
        ],
        "quaternion": [
          0,
          -0.6782645,
          0,
          0.7348178
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_vladimir",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0047117
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.2531661,
          0.5029945,
          -0.9354886
        ],
        "quaternion": [
          -0.1116374,
          -0.7140711,
          -0.1067517,
          0.6828203
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_vladimir",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038615
      }
    ]
  },
  "t90a_burlak": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.0350075,
          0.4436952,
          -1.6615637
        ],
        "quaternion": [
          -0.0709101,
          0.7976612,
          0.0530336,
          0.59657
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_burlak",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019486
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          0.9110822,
          0.6184152,
          -1.9710149
        ],
        "quaternion": [
          -0.0709101,
          0.7976612,
          0.0530336,
          0.59657
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_burlak",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0169582
      }
    ]
  },
  "t90sm": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.273,
        "pos": [
          1.5604846,
          0.3188142,
          -0.0525
        ],
        "quaternion": [
          -0.2387833,
          0.6655693,
          0.2387833,
          0.6655693
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0240628
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.273,
        "pos": [
          -1.5604846,
          0.3188142,
          -0.0525
        ],
        "quaternion": [
          -0.2387833,
          -0.6655693,
          -0.2387833,
          0.6655693
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0240628
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.19775,
          0.40152,
          -1.401456
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90sm",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t90m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5201626,
          0.173949,
          -0.7586891
        ],
        "quaternion": [
          0.13932,
          -0.7743919,
          0.1092811,
          0.6074247
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2643632
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2733235,
          0.5076844,
          -0.9704702
        ],
        "quaternion": [
          -0.3260054,
          -0.6973086,
          -0.2703507,
          0.5782662
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0134476
      }
    ]
  },
  "t90ms": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.0089731,
          0.7329723,
          -0.857424
        ],
        "quaternion": [
          -0.3780458,
          0.6207669,
          0.3572424,
          0.5866069
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90ms",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0152396
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1285579,
          0.5741697,
          -1.3246135
        ],
        "quaternion": [
          -0.1696276,
          0.7701519,
          0.1322612,
          0.6004993
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90ms",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0044683
      }
    ]
  },
  "t90m_proryv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5201626,
          0.173949,
          -0.7586891
        ],
        "quaternion": [
          0.13932,
          -0.7743919,
          0.1092811,
          0.6074247
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m_proryv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2643632
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.7620108,
          0.0576544,
          0.3875595
        ],
        "quaternion": [
          -0.1390394,
          -0.7239085,
          -0.1274581,
          0.6636105
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m_proryv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  }
});
