// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ua_t64bv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.2813689,
          0.3234875,
          -0.1265928
        ],
        "quaternion": [
          -0.02273,
          0.7529768,
          0.0198435,
          0.6573549
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t64bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0115407
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          0.9442993,
          0.6462092,
          -0.5662275
        ],
        "quaternion": [
          -0.363299,
          0.6538508,
          0.3223524,
          0.5801568
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t64bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0103427
      }
    ]
  },
  "ua_t80bv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.286,
          1.4066196,
          -1.2653581
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_t80bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.286,
          1.4066196,
          -1.6096552
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_t80bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ua_t80u_kursk": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2686408,
          0.2735146,
          -0.4226998
        ],
        "quaternion": [
          0.0386052,
          -0.8505849,
          0.0237771,
          0.5238794
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_kursk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153404
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4238485,
          0.2735062,
          -0.0474039
        ],
        "quaternion": [
          0.033276,
          -0.7847861,
          0.0262175,
          0.6183172
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_kursk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 1e-7
      }
    ]
  },
  "ua_t84_oplot_m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.531,
          0.364,
          0.5478
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t84_oplot_m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.1006951,
          0.6594564,
          -1.134184
        ],
        "quaternion": [
          -0.0805563,
          0.8319725,
          0.0529038,
          0.5463823
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t84_oplot_m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ua_m1a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          1.818,
          1.2676,
          -3.30724
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.27,
        "pos": [
          1.4603955,
          0.4995926,
          -0.1244897
        ],
        "quaternion": [
          -0.114204,
          0.6978234,
          0.114204,
          0.6978234
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
