// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "k2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.746,
          1,
          2.5
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.726,
          1,
          2.5
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5271339,
          0.327116,
          -0.4366394
        ],
        "quaternion": [
          -0.1197346,
          -0.7087162,
          -0.1158197,
          0.6855441
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "k2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
