// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "aft10_x": { v: 0.025, o: [-1.73, -0.00283, -3.7215], t: [0, 2.075, -1.65], g: [0, 2.8, -1.65], hull: "BgArABAAEwArABAAdgArABAAgwArABAAUABQAIIAUQBRAIMANQBPAIMANwBSAIQAPQBPAJEAPgBQAJMAUABPAJIAUgBQAJMATABQAJIATQBRAJMABwBHALgACABIALsAcwAfAN8AcwAtAN8AFwAeAPYAFwAuAPYA", turret: "MgBhACkAMgBjACwAVwBhACkAVwBjACwAPQBmAEUAPgBmAEwALABVAEwALABZAFEAJQBmAEwAJwBmAFkAYwBmAEwAZABmAFkALABaAE4ALABaAFkAQgBmAE4ASABmAE8A", gun: "YgB5ACgAYgB5AIAAZQB5ACgAZQB5AIAAEwB4AC8AJAB4ADMAKAB4AC8AOQB4ADMAUAB4AC8AYgB4ADMAZQB4AC8AdwB4ADMALABVAEQALABZAEsAYgBmAEQAYgBmAGUAZQBmAEQAZQBmAGUAKQBjAGMAOQBjAGMAUABjAGMAXwBjAGQAKwBjAGQAOQBjAGQA" },
});
