// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "ajax_x": { v: 0.025, o: [-2.183217, 0.173206, -4.365], t: [-0.05, 2.1, -1.05], g: [0, 2.506, 0.67], hull: "fAAkACQAfQAlACUAgAAkACQAiwAlACQAgAAkACUAgQAlACUAgwAlACUAhwAnACUAiAAmACUAjQAnACUAfwAjACYAfwAoACcATAAuACcATAA1ACgAgwArACgAkwArACgAowBGAD0AowBIAEEAowBGAHgAowBIAHwAowBGALIAowBIALYACAAxAOUACgA8AOsACQA9AOUACgA+APUACgA/AOUACgBEAPIACAAzAOwACgA8APEACAAxAPIACgAxAPUACAAyAPIACQA8APUACgA0APIACgA8APUACgA/APMACgBDAPUAVAA/ABEBWgA/ABIB", turret: "ZwB9AEwAdACBAE8AaACCAEwAcwCCAFcAbgBqAIAAbwBrAIEA" },
});
