// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "amx30_x": { v: 0.025, o: [-1.63, 0.35, -3.6293], t: [0, 1.584, 0.285], hull: "PwAOAAwAPwAPABEAQgAOAAwAQgAPABEAQAAPAAwAQQAPABIAPwAQAA8AQgAQABEA", turret: "LwBIAFEAPwBIAFMAQgBIAFEAUgBIAFMAKABbAHYALQBdAHYAGABBAH0AGABCAIIAFwBBAH8AFwBCAIYAFgBBAIIAFgBCAIwA" },
});
