// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "amx40_x": { v: 0.025, o: [-1.753, 0.0233, -3.537], t: [-0.039, 1.5629, 0.1682], hull: "CgA0AAgBDQA3AAkBfgA0AAgBgQA1AAkBIQBCAFoARABCAFoASABCAFoAagBCAFoADgA1AAYBFAA1AAcBdwA1AAYBfQA1AAcBCQA0AAgBCQA3AAoBCgA0AAoBDQA3AAoB", turret: "OABaAEgAawBbAEkAEQBLAD0AFABUAD0AGQBLAD0AKQBUAD0AEQBLAEEAFABSAEEAGQBLAEEAKQBSAEEAOABaAEcAawBbAEcAGwBPAEgAHABQAEwAIgBdAEgAQQBdAEsASwBdAEgAawBdAEsAOABbAEoAawBbAEwA" },
});
