// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "ares_apc_x": { v: 0.025, o: [-1.8345, 0.312, -3.3204], t: [-0.34515, 2.02518, 0.45243], g: [-0.38385, 2.7702, 0.3573], hull: "jgAhAEYAjgAoAEcAjgAxAEYAjgAyAEcAjgA5AEYAjgA6AEcAjgA9AEYAjgA+AEcAWwBIAEgAXQBIAEkAjgAhAGQAjgAoAGUAjgAxAGQAjgAyAGUAjgA5AGQAjgA6AGUAjgA9AGQAjgA+AGUAQABIAH4AQQBIAH8APwBIAH8APwBIAH8AjgAhAIMAjgAoAIMAjgAxAIMAjgAyAIMAjgA5AIMAjgA6AIMAjgA9AIMAjgA+AIMAjgAhAKEAjgAoAKEAjgAxAKEAjgAyAKEAjgA5AKEAjgA6AKEAMgBBAKEANABBAKEAdgBEAKIAdgBEAKIAMwBDAKYAMwBEAKYAMgBGAKYAMwBGAKYAMwBHAKYAMwBHAKYAMQBBAKcAMQBBAKcAKAA+AKgALAA+AKgALwBGAKgALwBGAKgAdQBBAK4AdQBBAK4AjgAhAL8AjgAoAMAAjgAxAL8AjgAyAMAAjgAhAN0AjgAoAN4ABQAiAPsAFgAiAPsAfAAiAPsAjQAiAPsA", turret: "PwBIAI0APwBIAI0AQgBIAI8AQgBIAI8AQwBIAJAAQwBIAJAAMgBIAJsAMgBIAJwA" },
});
