// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "ares_apc_x": { v: 0.025, o: [-2.03, 0.0504, -3.681], t: [-0.3835, 2.2502, 0.5027], g: [-0.4265, 3.078, 0.397], hull: "ZgBcAFAAZwBcAFEARgBbAIsASQBbAIsARgBbAIwASABbAIwAJQBaAKYAJQBaAKYAOABUALMAOgBUALMAggBXALQAggBYALQANwBWALgAOABWALgAOABXALgAOABXALgANwBaALgAOABaALgAOABbALgAOABbALgAOgBRALoAOgBRALoANABaALsANABaALsAMQBaALwAMQBaALwAjABaAMMAjABaAMMAKwAhACEBKwAhACEBLQAhACEBLQAhACEBdAAiACEBdAAjACEBdwAiACEBdwAjACEBLAAkACEBLAAkACEB", turret: "RABcAJwARQBcAJwARwBbAJ0ARwBbAJ0ARgBdAJ0ARwBdAJ0ASABbAJ4ASABbAJ4ASABdAJ4ASABdAJ4AOQBbAJ8AOQBbAJ8ASQBbAJ8ASQBbAJ8ASQBdAJ8ASQBdAJ8AOABbAKAAOABbAKEASgBbAKAASgBbAKAASgBdAKAASgBdAKAASwBbAKEASwBbAKEANwBbAKIANwBbAKMATABbAKMATABbAKQANgBbAKUANgBbAKgANgBbAKoANgBbAKsANwBdAKoANwBdAK0ANwBbAKsANwBcAK0AOABbAK0AOABbAK0A" },
});
