// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "ariete_c1_x": { v: 0.025, o: [-1.8614, 0.02105, -4.001373], t: [0, 1.462975, 0.367392], g: [0, 1.849679, 1.50254], turret: "JgBcAF0AJwBcAGsAJwBeAF4AJwBeAGoAJQBcAHMANQBcAHUAPgBeAJQAPwBfAJUAJgBfAJoAJgBiAJwALwBcAKgANQBdAKgAJQBdAKkAJwBeALEAJQBgAKkAJwBmAK8AIwBdAKoAJABmAKsAKABdAKoAKABmAKsAIgBeAKwAIwBlAK4AKABeAKwAKQBlAK4AJABgAKwAJABmAK8AQgBAALkAUgBMANMAQwBNALkAUQBOANMARABPALkAUABPANMARQBQALoATwBQANMARwBRALoATQBRANMA" },
  "ariete_c2_x": { v: 0.025, o: [-1.90452, 0.02105, -4.001373], t: [0, 1.462975, 0.367392], g: [0, 1.849679, 1.50254], turret: "JwBcAF0AKABcAGsAIABbAGIAIABbAHsAJgBbAHMAJwBcAHUAKABcAHMANwBcAHUAQABeAJQAQQBfAJUAKABfAJoAKABiAJwAOABeAKYAOQBfAKcARABAALkAVABMANMARABNALkAUwBNANMARQBOALkAUgBOANMARgBPALkAUgBPANMARwBQALoAUABQANMASQBRALoATwBRANMAIABUAMoAIABWAM8A" },
});
