// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "ariete_c1_x": { v: 0.025, o: [-1.67, 0.0101, -3.5807], t: [0, 1.3062, 0.328], turret: "IABWAJgAIwBbAJsAJABUAJoAJQBbAJsAIgBWAJwAIwBbAJ0APAA6AKYASQBFAL0APgBGAKYARwBHAL0AQgBIAKYAQwBJAL0AIABSAGcAKABSAGkAKQBTAGkAOgBTAGkASQBTAGkAVgBTAGkAIgBTAJcAIgBUAJ8AIABTAJgAIQBUAJ0AJABVAJgAJABcAJkAIQBcAJgAIwBcAJ0AHwBTAJkAHwBcAJwAJABUAJwAJQBbAJwAIABWAJwAIQBbAJwAOwA6AKYAOwBEAL0APABGAKYAPQBGAL0ASABGAKYASABGAL0APQBHAKYAPQBHAL0APwBIAKYAQQBIAL0ARABIAKYARgBIAL0AQQBJAKYAQQBJAL0ARABJAKYARABJAL0A" },
});
