// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "bmp3m_dragun125_x": { v: 0.022500000000000003, o: [-1.5975, 0.4041, -3.5919000000000003], t: [0, 1.8, -1.08], g: [0, 2.0326500000000003, 0.387] },
});
