// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "bmp3m_dragun125_x": { v: 0.025, o: [-1.605, 0.3966, -3.5994], t: [0, 1.8, -1.08], g: [0, 2.03265, 0.387], gun: "PgBBAEIBPgBBAEcB" },
});
