// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "borsuk": { v: 0.025, o: [-1.8025, 0.345, -3.894], t: [0, 2.02, -0.62], g: [0, 2.54, 0.55], turret: "dwBVAG0AgABaAHkAgQBWAG0AgQBbAKAAggBYAG0AggBYAKYAdwBbAG0AeABkAHkAegBbAG0AgABcAKAAfABdAG0AfgBlAKAAewBeAG0AewBlAKAAfwBeAG0AfwBlAKAAegBfAG0AegBlAKAAgABfAG0AgABlAKAAeQBgAG0AeQBkAKAAgQBgAG0AgQBlAKAAggBiAG0AggBiAKYAeQBVAHoAgABaAJMAdwBVAIkAeABVAJMAdwBVAJQAdwBVAJQAegBVAJQAgABaAJQAeQBWAJQAeQBaAKAAewBVAJUAgABaAKAAegBWAJUAegBaAKAAegBVAJcAegBVAKAAfABVAKEAfgBbAKIAewBWAKEAewBbAKIAfwBWAKEAfwBbAKIAegBXAKEAegBZAKIAgABXAKEAgABaAKIAegBcAKEAegBcAKIAfABdAKEAfABdAKYAfgBdAKEAfgBdAKIAfABfAKEAfgBlAKIAewBgAKEAewBlAKIAfwBgAKEAfwBlAKIAegBhAKEAegBjAKIAgABhAKEAgABkAKIAegBcAKUAegBcAKYAfgBdAKUAfgBdAKYA" },
});
