// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "borsuk": { v: 0.025, o: [-1.62975, 0.303, -3.5121], t: [0, 1.818, -0.558], g: [0, 2.286, 0.495], turret: "awBNAGIAdABRAG0AdQBOAGIAdQBRAJAAawBSAGIAbABaAGUAbgBSAGIAdABTAJAAcABUAGIAcgBbAJAAbwBVAGIAbwBbAJAAcwBVAGIAcwBbAJAAbgBWAGIAbgBbAJAAdABWAGIAdABbAJAAbQBXAGIAbQBaAJAAdQBXAGIAdQBaAJAAawBbAGIAawBbAG4AbABSAGYAbABaAG0AawBTAGYAawBaAG0AawBSAGgAawBSAG0AbQBNAG4AdABRAIUAbABNAHwAbABNAIUAawBSAHwAawBSAH8AawBSAIIAawBSAIwAbgBNAIYAdABRAIYAbQBOAIYAbQBRAJAAbwBNAIcAdABRAJAAbgBOAIcAbgBRAJAAFgBJAIgAFgBJAIgAbgBNAIgAbgBNAJAAcABNAJEAcgBSAJIAbwBOAJEAbwBSAJIAcwBOAJEAcwBSAJIAdQBOAJEAdQBOAJIAbgBPAJEAbgBQAJIAdABPAJEAdABQAJIAdABTAJEAdABTAJIAcABUAJEAcABUAJIAcgBUAJEAcgBUAJUAcABWAJEAcgBbAJIAbwBXAJEAbwBbAJIAcwBXAJEAcwBbAJIAdQBXAJEAdQBXAJIAbgBYAJEAbgBZAJIAdABYAJEAdABZAJIAdQBOAJUAdQBOAJUAcABUAJUAcABUAJUAdQBXAJUAdQBXAJUA" },
});
