// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "chieftain5_x": { v: 0.025, o: [-1.724, 0.274, -3.7338], t: [0.0031, 1.476, 0.3693], hull: "IAAqAA4AJQArAA8AZAAsAA4AZwAtAA8AQgAwAMwARwAxAM8APAAwAM4AQQAxAM8ASAAwAM4ATQAxAM8AOgAwANAAPQAxANEAQAAwAOAASQAxAOEAJAAoAAQBJwApAAcBKgAoAAQBLQApAAcBWgAoAAQBXwApAAcBYgAoAAQBZQApAAcBJAAmAAYBJwAnAAcBKgAmAAYBLwAnAAcBWgAmAAYBXwAnAAcBYgAmAAYBZQAnAAcBZQAkAA4AZgAmAA8AIAAsAA4AJQAsAA8AZAAqAA8AaQArAA8AIAAtAA8AJQAuAA8ACAAqABgACwAqABsAfgAqABgAgAAqABsACAAqAEIACgAqAEYAfgAqAEIAgAAqAEYACAAqAFEACwAqAFUAfgAqAFEAgAAqAFUAIQA1AG0APAA2AG0ATQA1AG0AZwA2AG0AQwAxANAATQAxANIAQAAxANwASQAxAN8AIwAnAAMBKAApAAMBKgAnAAMBLgApAAMBXAAnAAMBXwApAAMBYQAnAAMBZgAoAAMBIwAnAAQBKAAnAAUBKgAnAAQBLwAnAAUBWgAnAAQBXwAnAAUBYQAnAAQBZgAnAAUBKgAlAAgBLwAnAAgBWgAlAAgBXwApAAgBJAAmAAgBJwApAAgBYgAmAAgBZQApAAgB", turret: "agBFAFMAagBNAFgAagBBAFQAagBEAFgAgABAAFkAhgBAAFoAagBBAFsAagBNAFsAbQA+AGwAdwA/AGwAEABAAHsAGQBLAHsAcwA+AIkAhQBNAIkAhwA/AIkAhwBNAIoAhgBAAIkAhgBNAIoAcgBCAIkAcgBNAIkAcABHAIkAcABNAIoAcwA+AIoAhQBFAIoAcwBGAIoAggBNAIoA" },
});
