// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "cv90_mkiv_x": { v: 0.025, o: [-1.7114, 0.225, -3.369], t: [-0.035, 1.55, -0.6], g: [0.172, 1.844, 0.7], turret: "LwBTAEoALwBZAFEAaABVAEsAaQBVAFEAEABPAHMAEABRAIkAFwBPAHMAFwBSAIkAHQBPAHMAHQBRAIkAFwBOAHQAFwBOAIoADwBNAHUADwBNAIoAHABNAHUAHABNAIoADwBSAHUADwBSAIAAHABSAHUAHABSAIAAGABNAHgAGABNAIoAcABUAHoAcQBVAHsA" },
});
