// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "cv90_x": { v: 0.025, o: [-1.7875, 0.295, -3.532], t: [0, 1.78, -0.76], g: [0, 2.185, 0.8], hull: "CwAkAA0ACwAkAA0AgwAkAA0AgwAkAA0AFQBDABEAFQBDABEAeQBDABEAeQBDABEA", turret: "IwBbAIIAIwBbAIIAawBbAIIAawBbAIIA" },
});
