// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "dardo": { v: 0.025, o: [-1.6415, 0.028234, -3.459], t: [0, 1.72, -0.3], g: [0, 2.12, 0.65], hull: "EQA7AOgAEgA8AOgAcAA7AOgAcQA7AOgAcAA8AOgAcAA8AOgAFAA5AOkAFAA5AOoAbgA5AOkAbgA6AOkAFAA6AOoAFAA6AOoAcQA7AOoAcQA7AOoA", turret: "NABgAH0ANABgAH0A" },
});
