// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "fv510_milan_x": { v: 0.025, o: [-2.1875, 0.2249, -3.330474], t: [0.175, 1.965, -0.42], g: [0.114, 2.23, 0.7], hull: "GQAlABkAHQAnAB4AkQAlABkAkQAnAB4AGAAlABoAGAAnAB4AkgAmABoAlQAnAB0AEgBAAB8AFQBAACEAmgBAACAAmwBBACEAEgBAAE4AFQBAAFAAmgBAAE4AmwBBAE8AmgBAAHwAmwBBAH8AEgBAAH0AFQBAAH8AEgBAAKsAFQBAAK4AmgBAAKwAmwBBAK0AMAAlAAIBfgAmAAIB", turret: "SgBLAEsAWwBLAEsAYQBLAEsAbwBLAEsASgBOAEsAWwBOAEsAYQBOAEsAbwBOAEsAUQBRAEsAWwBRAEwAYQBRAEsAbgBRAEsAPQBQAGcAPQBQAHsAPQBSAGgAPwBTAHsAQABTAGgAQABTAIkAPQBPAG4APQBPAHsAPgBQAHEAPgBQAIcAQABSAHkAQABSAIkAQQBTAHsAQQBTAIkAPgBSAHwAPwBTAIcARwBcAIUAUgBfAIUAagBcAIUAdQBfAIYASABcAIYAUQBfAIYARwBcAIcAUgBeAIsAagBcAIcAdQBeAIkAQQBSAIgAQQBSAIkAQgBSAIoAQwBTAIsAegBSAIoAewBTAIsAagBcAIoAcwBeAIsAdABeAIoAdQBeAIsA" },
});
