// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "griffin50_x": { v: 0.025, o: [-1.97461, 0.248, -3.49314], t: [0, 2.07, -0.396], g: [0, 2.547, 0.594], hull: "fQAxACYAkwAxACYABwAXAIMABwAZAIkAlgAXAIMAlgAZAIkACgAyAMUACgBCAMUACgAyAMYACgBBAMsAVABHAMsAVwBHAM0ACgAyAMwACgBAANEARwBHAMwAUwBHAM0AOgBHAM0ARgBHAM0ATQBGAM8AVwBGANMABwAXANAABwAZANYAlgAXANAAlgAZANYAPwBGANAATABGANMAMgBGANEAPgBGANMACgAyANIACgA/ANcAJQBGANIAMQBGANMACgAyANgACgA+ANkA", gun: "TQBVAJsAUABXAJsA" },
});
