// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "griffin50_x": { v: 0.025, o: [-1.97461, 0.248, -3.1824], t: [0, 2.07, -0.36], g: [0, 2.6, 0.74], hull: "BwAYAHcABwAZAH0AlgAYAHcAlgAZAH0ACgAyALQACgBBALgACgAyALkACgBAAL4AUgBHALkAVwBHALsAQgBHALoAUQBHALsANQBHALsAQQBHALsAUwBGALwAVwBGAMAABwAXAL0ABwAZAMMAlgAXAL0AlgAZAMMARABGAL0AUgBGAMAANgBGAL4AQwBGAMAACgAyAL8ACgA/AMMAKABGAL8ANQBGAMAACgAyAMQACgA+AMUA", turret: "ZQBeAJ4AZwBhAJ4A", gun: "SwBXAJMAUgBaAJMASwBXAJQAUgBYAJQA" },
});
