// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "jpz_e100_x": { v: 0.025, o: [-2.3144, -0.045, -4.413], t: [-0.0007, 2.338, 0.2], hull: "LAAwAEIBMwAxAEcBhgAwAEIBjQAxAEcBMgAuAEQBMwAvAEcBhgAuAEQBhwAvAEcBMgAsAEYBMwAtAEcBhgAsAEYBhwAtAEcBRgBHAAYAcgBHAAcANABLAOEAOwBLAOIAfQBLAOEAhABLAOIAKwAyADsBMwAyAEcBhQAyADsBjQAyAEcBKwAxAD8BMwAxAEEBhQAxAD8BjQAxAEEBKwAwAEIBKwAxAEcBhQAwAEIBhQAxAEcB" },
});
