// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "jpz_e100_x": { v: 0.025, o: [-2.31442, 0.3448, -4.413], t: [-0.0007, 2.33805, 0.2], g: [-0.0007, 2.33805, 0.2], hull: "RgA4AAYAcgA4AAcAPgBzAGcAQgB0AGgAMAAiAD0BMwAiAEcBhQAiAD0BiAAiAEcBMQAgAEIBMwAhAEcBhQAgAEIBhwAhAEcBMgAeAEQBMwAfAEcBhgAeAEQBhwAfAEcBMgAcAEYBMwAdAEcBhgAcAEYBhwAdAEcB", gun: "WAA5AMAAXwA5AMQA" },
});
