// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "k1a1_x": { v: 0.025, o: [-1.9129, 0.0251, -3.8865], t: [0, 1.49566, 0.42564], g: [0.0352, 1.81797, 1.57716], hull: "JAAzAAkBKQAzAA8BbwAzAAkBdAAzAA8BJAAyAA8BKQAyABIBbwAyAA8BdAAyABIBJQAyABMBKQAyABgBbwAyABMBcwAyABgBJQAxABYBKQAxABgBbwAxABYBcwAxABgBJgAwABkBKQAyABkBbwAwABkBcgAyABkBKAAwABoBKQAxABsBcAAwABoBcQAxABsBBQA1ABsBBwA1AB8BkQA1ABsBkwA1AB8B", turret: "aQBNAFAAawBSAFAAWQBHAGIAWQBSAGIAWwBNAGcAXwBUAGcAWQBOAGgAXwBSAGgAWgBTAGgAXwBUAGsAWQBQAGkAYABSAGsAYABTAGkAYABUAGsAXABSAGwAXQBUAGwAWgBUAGwAWwBUAGwAXgBUAGwAXwBUAGwAXABSAG0AXQBTAG0AMgBSAHAAWQBSAHAANABUALAANwBXALIAOABUALIAOQBXALIAJABWALwANwBYAMYAJQBZALwANwBaAMYAJABVAL0ANwBVAMYAJABUAL8ANwBUAMcAPgA9AMYAWABNAMgAPgA9AMkAWABMANAAPgA9ANEAWABLANkAQAA9ANoARABIANoAUgA9ANoAVgBIANoA" },
});
