// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "k1a1_x": { v: 0.025, o: [-1.9129, 0.0246, -3.8865], t: [0, 1.4957, 0.4256], hull: "KAAwABoBKQAxABsBcAAwABoBcQAxABsBJAAzAAkBKQAzAA8BbwAzAAkBdAAzAA8BJQAyABABKQAyABgBbwAyABABcwAyABgBJQAxABYBKQAxABgBbwAxABYBcwAxABgB", turret: "WgBQAGgAXwBTAGsAXABSAGwAXQBTAG0ANABUALAANwBXALEAJABWALwANwBZAMUAJABUAMAANwBVAMUAPgA+AMYAVwBNAMcAPgA+AMgAVwBLANkAcQBNADsAdABPADsAewBHADwAfABJAD0AbwBGAFAAbwBSAFAAcABHAFAAcQBSAFAAaQBNAFAAawBSAFAAWQBHAGIAWQBSAGIAWQBJAGMAWQBSAGQAWwBNAGcAXwBUAGcAWQBOAGgAXwBPAGgAWQBQAGgAWQBSAGsAWgBUAGgAXwBUAGwAYABQAGkAYABUAGsAMgBSAHAAWQBSAHAAOgBUAK8AOgBYALIANABUALIAOQBXALIAJABaALwANwBaAMYAJABVAL0ANwBVAL8AJABUAL8ANwBUAL8APgA9AMYAWAA9ANkAWAA+AMYAWABNAMgAJABUAMYANwBZAMYAJABUAMcANwBUAMcAPgBMAMgAVwBNAMgAWAA+AMkAWABMANAAPgBMAMkAVwBMANAAWAA+ANEAWABLANkA" },
});
