// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "k2_x": { v: 0.025, o: [-1.935, 0.3555, -4.0017], t: [0, 1.5945, 0.2181], hull: "KgAkACgBLwAlACkBagAkACgBbwAlACkBEwAlACYBIgAlACYBJwAlACYBMgAlACcBZwAlACYBcgAlACcBeAAlACYBhwAlACYBFQAkACgBIgAkACgBeAAkACgBhAAkACgBFwAkACkBIgAkACkBeAAkACkBgwAkACkBKgAlACoBMAAlAC0BagAlACoBcAAlAC0B", turret: "IABCAEgALwBDAEsAIABGAEgALwBHAEsAIABCAEwAJQBDAE0AIABGAEwAJQBHAE0ARgBSAGIARwBTAGMAMgA8AEYAMgBPAEYAHwA8AEcAMABIAEcAHwA8AEgAMABBAEgAIABEAEgALwBFAEgAIABIAEgALwBIAEgAHwBBAEkAMABBAEwAHwBFAEkAMABFAEwAJgBCAEwALwBDAEwAJgBGAEwALwBHAEwALQBRAG4AMgBRAHQAbABRAG4AbABRAH8AbQBRAHEAbgBRAHsA" },
});
