// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "kf41_lynx_x": { v: 0.025, o: [-1.7031, 0.04155, -3.612], t: [0, 2.061, -0.135], g: [-0.010476, 2.343024, 0.63], turret: "LABrAIcAOgBtAIcATgBrAIcAWwBtAIcATQBtAIcATQBtAIcAXABtAIcAXABvAIcAUABuAIcAWwBvAIcAXQBuAIcAXQBvAIcAPQBrAKAAPQBrAKEASgBrAKAASwBrAKEAPABrAKEAPABrAKEAMgBgAMQANwBhAMQAUABgAMQAVwBhAMQALwBhAMYALwBhAMYALwBfAMcALwBfAMcAWwBfAMcAYgBfAMcAMABdAMgAMABeAMkAMQBeAMgAMQBeAMkALwBbAMkALwBbAMkAMABcAMkAMQBcAMkAMQBdAMkAMQBdAMkA" },
});
