// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "kurganets25_x": { v: 0.025, o: [-1.955, 0.46, -3.805], t: [0, 2.21, -1.27], g: [-0.004, 2.917, -0.68], hull: "SQAPAAcAVwAPAAcAeABGAIMAhgBGAIMAewA/AM4AfQA/ANIAewA+ANcAfQA+ANoALAAbABwBcAAbABwBLAAdAB4BcAAeAB4BEgAfAB8BiQAfAB8BEgAgAB8BKgAhAB8BcQAgAB8BiQAhAB8BEgAgACABiQAgACABEgAlACMBiQAlACMBEwArACcBKgArACcBcQArACcBiAArACcBLgAuACsBNAAvACsBOAAuACsBZAAwACsBaAAuACsBbQAwACsBNwAwACwBZAAyACwB", turret: "ZgBzABcAZgBzADYAYwB2ABcAYwB2ADYARgBpAFYAWABqAFgALQBoAFwAQgBoAFwAVgBbAGkAVgBcAG4ASABeAG4AVQBeAG4AUwBfAG4AVQBiAG4A", gun: "SQBeAG8AUgBeAHkAdgBZAHEAdwBaAHQAdQBaAHEAdQBaAH0AUwBeAHQAUwBkAHcAdgBYAHUAdgBaAHsA" },
});
