// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "kurganets25_x": { v: 0.022500000000000003, o: [-1.7595, 0.41400000000000003, -3.4245], t: [0, 1.989, -1.143], g: [-0.0036000000000000003, 2.6252999999999997, -0.6120000000000001], hull: "SQAPAAcAVwAPAAcAeABGAIMAhgBGAIMAewA/AM4AfQA/ANIAewA+ANcAfQA+ANoALAAbABwBcAAbABwBLAAdAB4BcAAeAB4BEgAfAB8BiQAfAB8BEgAgAB8BKgAhAB8BcQAgAB8BiQAhAB8BEgAgACABiQAgACABEgAlACMBiQAlACMBEwArACcBKgArACcBcQArACcBiAArACcBLgAuACsBNAAvACsBOAAuACsBZAAwACsBaAAuACsBbQAwACsBNwAwACwBZAAyACwB", turret: "ZgBzABcAZgBzADYAYwB2ABcAYwB2ADYARgBpAFYAWABqAFgALQBoAFwAQgBoAFwAVgBbAGkAVgBcAG4ASABeAG4AVQBeAG4AUwBfAG4AVQBiAG4A", gun: "SQBeAG8AUgBeAHkAdgBZAHEAdwBaAHQAdQBaAHEAdQBaAH0AUwBeAHQAUwBkAHcAdgBYAHUAdgBaAHsA" },
});
