// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "kurganets25_x": { v: 0.025, o: [-1.767, 0.4065, -3.27774], t: [0, 1.989, -1.143], g: [-0.0036, 2.6253, -0.612], hull: "EAAhAPoAFAAhAPoAeAAhAPoAfAAhAPoA", gun: "SwBaAGYASwBaAGYA" },
});
