// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "leclerc_x": { v: 0.025, o: [-1.7791, -0.0017, -3.6402], t: [-0.0022, 1.4029, 0.7212], hull: "bgA/AB4AhgA/AB4A", turret: "GgBOAEwAHwBPAE0AGABOAE4AGwBPAE8AFgBOAFAAFwBPAFEALABUAIgAOQBVAJEAEwBTADYAPABTADYAEgBWADYAPABWADYADABPAEUADABPAFEADABWAEUADABWAFEAGwBNAEsAIgBPAEsAIwBOAEsAPQBPAEsAQwBQAEsARABRAE0AQwBUAEsARABVAE0AIwBPAEwAPQBPAE0ALABUAJIAOQBVAJIA" },
});
