// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "leclerc_x": { v: 0.025, o: [-1.7791, -0.0085, -3.640153], t: [-0.002153, 1.40295, 0.721229], g: [0.018886, 1.879106, 1.99888], turret: "TQBRAE4ATQBRAFEATgBRAE8ATgBRAFEALABUAIgAOQBVAJIAZABiALUAZABkALsA" },
});
