// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "leclerc_x": { v: 0.025, o: [-1.7791, -0.001744, -3.640153], t: [-0.002153, 1.40295, 0.721229], g: [0.018886, 1.879106, 1.99888], hull: "bgA/AB4AhgA/AB4AbgA+ACsAhgA+ACsA", turret: "EwBTADYAPABTADYAEwBNADgAEwBNADgAFgBNADgAHgBNADgAIQBNADgAKwBNADgALgBNADgANwBNADgAOwBNADgAPABNADgAEQBTADgAEQBTADgAEQBNADoAEQBNADoAQABTADwAQABTADwAQABNAD4AQABNAD4AQgBNAEEAQgBNAEEAQgBNAEMAQgBOAEMAQgBSAEMAQgBTAEMAGwBNAEsAIgBOAEsAIwBOAEsAPQBOAEsAQwBQAEsARABRAE0AQwBUAEsARABWAE0AGgBNAEwAIABOAEwAIQBOAEwAIgBOAEwAGQBNAE0AHgBOAE0AHwBOAE0AIABOAE0AFwBNAE4AHABOAE4AHQBOAE4AHgBOAE4AQwBQAE4ARABQAE8ATQBQAE4ATQBQAE8AFgBNAE8AGgBOAE8AGwBOAE8AGwBOAE8ATgBQAE8ATgBQAE8AFQBNAFAAGABOAFAAGQBOAFAAGQBOAFAAEwBNAFEAFQBOAFEAFgBOAFEAFwBOAFEALABUAIgAOQBVAJIAZABiALUAZABjALsA" },
});
