// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "leclerc_classic_x": { v: 0.025, o: [-1.875, 0.0014, -3.7946], t: [-0.0163, 1.477, 0.5611], hull: "VQA9AOIAbQA+AOUAVQA/AOMAbQA/AOMAVQA9AOYAbQA9AOcACQArACEBGAAsACEBfQArACEBjAAsACEB", turret: "XABmALYAZQBxALkALABaAMoAOwBbAN8ALABSANgAOwBZAN8ADQBOAEAADQBOAE4ADQBQAEAADQBQAE4AUABVAEQAUABWAEkARgBXAEcARgBZAEoAXABlALUAZgBxALUAXABlALYAZgBlALoAZgBmALYAZgBxALoAXABmALoAZQBxALoALABRANkAOwBRAOAALABQAN8AOwBQAOAALABSAOAAOwBbAOAA" },
});
