// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "lrmv_lynx": { v: 0.025, o: [-1.884, 0.032475, -4.005], t: [0, 2.29, -0.15], g: [-0.01164, 2.60336, 0.7], turret: "fABxAHoAfABxAHoA" },
});
