// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "marder2": { v: 0.025, o: [-2.020434, 0.057286, -3.82], t: [0, 2.02, -0.48], g: [0, 2.56, 0.64], hull: "DABGAB4ADABGAB4ADABGADYADABGADYADABGAEMADABGAEMADABGAGAADABGAGAADABGAG0ADABGAG0ADABGAIUADABGAIUAGgBCAAkBGgBLAAkB", turret: "WwBzAIEAWwBzAIEAXwBeAI4AXwBqAJcARABbAKIARABlAKcAQgBeAKIAQwBlAKcAYQBQAKgAYwBQAKgAQgBeAKgAQgBgAKoAQgBhAKkAQgBhAKoAQgBkAKkAQgBlAKoAQgBpAKkAQgBqAKoAQgBiAKoAQgBjAKoAQgBeAKwAQgBgAKwAXgBeAKwAXwBgAKwAQgBeAK0AQwBfAK0AXgBeAK0AXwBfAK0AQgBeAK4AQwBeAK4AXQBeAK4AXwBeAK4A", gun: "XgBeAKgAXgBeAKsAQwBeAKkAQwBeAKwAXgBfAKkAXgBfAKsAQwBfAKsAQwBfAKwAXgBgAKsAXgBgAKsAXQBeAKwAXQBeAK0ARABeAK4ARABeAK4A" },
});
