// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "cn_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], hull: "dwAmAOkAdwAmAOkA", turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAPAA6AJwAPQA6AJwAWAA6AJwAWQA6AJwAPABCAJwAPABEAJwAWQBCAJwAWQBEAJwAPQBDAJwAPQBEAJwAWABDAJwAWABEAJwAPgBEAJwAVwBEAJwA" },
  "cn_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], hull: "IwAqAOgAJAAqAOgAIwAoABABJwAoABABegAoABABfgAoABAB", turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA6AKIAQwA7AKIAQwA7AKIAXwA7AKIAXwA7AKIAQwAzAKMAXwA5AKQAQwA6AKMARAA6AKMAXgA6AKMAXwA6AKMAQwAxAKQAQwAyAKQAXwAxAKQAXwAyAKQARAAyAKQAXgAyAKQAQwA6AKQAQwA6AKQAXwA6AKQAXwA6AKQAQwBHAKQAQwBHAKQAXwBHAKQAXwBHAKQA" },
  "cn_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "XQAuAGwAXQAuAGwAOQA4AJsAVgBBAJsAOQA1AJwAVgA6AJwAOQA7AJwAOQA7AJwAVgA7AJwAVgA7AJwAOQBCAJwAOQBEAJwAOgBEAJwAOgBEAJwA" },
  "pl_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], hull: "dwAmAOkAdwAmAOkA", turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAPAA6AJwAPAA6AJwAWQA6AJwAWQA6AJwAPABDAJwAPABEAJwAWQBDAJwAWQBEAJwAPQBEAJwAWABEAJwA" },
  "pl_t72b3_zubr_ii": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], hull: "dwAmAOkAdwAmAOkA" },
  "pl_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], hull: "IwAqAOgAJAAqAOgAIwAoABABJwAoABABegAoABABfgAoABAB", turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA6AKIAQwAzAKMAXwA5AKQAQwA6AKMAQwA6AKMAXwA6AKMAXwA6AKMAQwAxAKQAQwAyAKQAXwAxAKQAXwAyAKQARAAyAKQAXgAyAKQA" },
  "pl_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "XQAuAGwAXQAuAGwAOQA4AJsAVgBBAJsAOQA1AJwAVgA6AJ0AOQA7AJwAOQA7AJ0AVgA7AJwAVgA7AJwAOQAzAJ0AVgA0AJ0A" },
  "ru_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], hull: "dwAmAOkAdwAmAOkA", turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAWQA6AJwAWQA6AJwA" },
  "ru_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], hull: "IwAqAOgAJAAqAOgAIwAoABABJwAoABABegAoABABfgAoABAB", turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA6AKIAQwAzAKMAXwA5AKQAQwAxAKQAQwAyAKQAXwAxAKQAXwAyAKQARAAyAKQAXgAyAKQA" },
  "ru_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "XQAuAGwAXQAuAGwAOQA4AJsAVgBBAJsAOQA1AJwAVgA6AJ0AOQA7AJwAOQA7AJwAOQAzAJ0AVgA0AJ0A" },
  "ua_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], hull: "dwAmAOkAdwAmAOkA", turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAWQA6AJwAWQA6AJwA" },
  "ua_t72b3m_hetman_ii": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.445, 0.114315], g: [0.008, 1.875, 1.014315], hull: "IwAqAOgAJAAqAOgAIwAoABABJwAoABABegAoABABfgAoABAB" },
  "ua_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], hull: "IwAqAOgAJAAqAOgAIwAoABABJwAoABABegAoABABfgAoABAB", turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA6AKIAQwAzAKMAXwA5AKMA" },
  "ua_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "XQAuAGwAXQAuAGwAOQA4AJsAVgBBAJsAOQA1AJwAVgA6AJwAOQA7AJwAOQA7AJwA" },
});
