// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "cn_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.475, 0.065591], g: [0.001, 1.84609, 1.266591], gun: "QABHALIAVwBHALoAQABGALYAVwBGALcA" },
  "cn_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.545, 0.114315], g: [0.001, 1.91609, 1.315315], gun: "TgBIALkAUwBIAMAATABIALoATQBIAMAAVABIALoAVQBIAMAARgBHALsAXwBHAMEAVgBIALsAVwBIAMAASQBHAMIAWQBHAMIAUwBFAMYAXgBFAMYA" },
  "cn_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.565, 0.07187], g: [0.001, 1.93609, 1.27287] },
  "pl_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.475, 0.065591], g: [0.001, 1.84609, 1.266591], gun: "QABHALIAVwBHALoAQABGALYAVwBGALcA" },
  "pl_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.545, 0.114315], g: [0.001, 1.91609, 1.315315], gun: "TgBIALkAUwBIAMAATABIALoATQBIAMAAVABIALoAVQBIAMAARgBHALsAXwBHAMEAVgBIALsAVwBIAMAASQBHAMIAWQBHAMIAUwBFAMYAXgBFAMYA" },
  "pl_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.565, 0.07187], g: [0.001, 1.93609, 1.27287] },
  "ru_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.475, 0.065591], g: [0.001, 1.84609, 1.266591], gun: "QABHALIAVwBHALoAQABGALYAVwBGALcA" },
  "ru_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.545, 0.114315], g: [0.001, 1.91609, 1.315315], gun: "TgBIALkAUwBIAMAATABIALoATQBIAMAAVABIALoAVQBIAMAARgBHALsAXwBHAMEAVgBIALsAVwBIAMAASQBHAMIAWQBHAMIAUwBFAMYAXgBFAMYA" },
  "ru_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.565, 0.07187], g: [0.001, 1.93609, 1.27287] },
  "ua_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.475, 0.065591], g: [0.001, 1.84609, 1.266591], gun: "QABHALIAVwBHALoAQABGALYAVwBGALcA" },
  "ua_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.545, 0.114315], g: [0.001, 1.91609, 1.315315], gun: "TgBIALkAUwBIAMAATABIALoATQBIAMAAVABIALoAVQBIAMAARgBHALsAXwBHAMEAVgBIALsAVwBIAMAASQBHAMIAWQBHAMIAUwBFAMYAXgBFAMYA" },
  "ua_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.565, 0.07187], g: [0.001, 1.93609, 1.27287] },
});
