// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "cn_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAPgBEAJwAVwBEAJwA" },
  "cn_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA1AKQARAA2AKIAXwA6AKIAQwAzAKMAXwA0AKQARAA2AKMAXwA5AKQARAAyAKQAXgAyAKQA" },
  "cn_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "OQA4AJsAVgBBAJsAOQA1AJwAVgA6AJwA" },
  "pl_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwAPQBEAJwAWABEAJwA" },
  "pl_t72b3_zubr_ii": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591] },
  "pl_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA1AKQARAA2AKIAXwA6AKIAQwAzAKMAXwA0AKQARAA2AKMAXwA5AKQARAAyAKQAXgAyAKQAQwA2AKQAQwA5AKQA" },
  "pl_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "OQA4AJsAVgBBAJsAOQA1AJwAVgA1AJ0AOQA2AJwAVQA6AJ0AOQA7AJwAOQA7AJ0AOQAzAJ0AVgA0AJ0A" },
  "ru_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwA" },
  "ru_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA1AKQARAA2AKIAXwA6AKIAQwAzAKMAXwA0AKQARAA2AKMAXwA5AKQARAAyAKQAXgAyAKQA" },
  "ru_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "OQA4AJsAVgBBAJsAOQA1AJwAVgA1AJ0AOgA2AJwAVQA6AJ0AOQAzAJ0AVgA0AJ0A" },
  "ua_t72b3_modern": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0.008, 1.39, 0.065591], g: [0.008, 1.82, 0.965591], turret: "PAA2AJsAWQBBAJsAPAAzAJwAWQA5AJwA" },
  "ua_t72b3m_hetman_ii": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.445, 0.114315], g: [0.008, 1.875, 1.014315] },
  "ua_t72b3m_modern": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.46, 0.114315], g: [0.008, 1.89, 1.014315], turret: "QwA4AKEAXwBAAKEAQwA1AKIAXwA1AKMARAA2AKIAXwA6AKIAQwAzAKMAXwA0AKMARAA2AKMAXwA5AKMA" },
  "ua_t80u_modern": { v: 0.025, o: [-1.797, 0.403, -3.435], t: [0.008, 1.49, 0.07187], g: [0.008, 1.92, 0.97187], turret: "OQA4AJsAVgBBAJsAOQA1AJwAVgA6AJwA" },
});
