// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "pl01": { v: 0.025, o: [-1.997, 0.225, -3.71], t: [0, 2.07, -0.9], turret: "LgBkAD4ALwBlAD8AcABkAD4AcQBlAD8APwBjADgAQgBjAD4A" },
  "pl01_105": { v: 0.025, o: [-1.997, 0.225, -3.71], t: [0, 2.07, -0.9], turret: "LgBkAD4ALwBlAD8AcABkAD4AcQBlAD8AQgBmAD4ARQBnAD8APwBjADgAQABjAEEAPwBkAD4AQABmAEAAQQBlAD4ARABlAEAARQBjAEgAWQBjAEgAUABjAEkAWQBjAE0A" },
  "pt91_twardy": { v: 0.025, o: [-1.9315, 0.3289, -3.501], t: [0, 1.38, 0.02], hull: "QAAsAN4AQQAtAN8ANQAwABcAQQAwABkAWQAwABcAZAAwABkANAAqAOAAOQAqAOQA" },
  "t72m1_jaguar": { v: 0.025, o: [-1.87, 0.3489, -3.3725], t: [0, 1.4, 0.1], hull: "jAAlAFsAjQAmAF4AIAAdAAgBIwAdAAoBcQAdAAgBdAAdAAoB", turret: "agA6AK4AawA7AK8AQQBDAGAATQBEAGAAaQA8AKwAagA8ALEA" },
});
