// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "spz_puma_s1_x": { v: 0.025, o: [-2.103, 0.051988, -3.883], t: [0.434794, 1.947494, -1.319322], g: [0.019503, 2.51311, -0.791446], hull: "HABLABoAHABLABoAGQBMABsAGgBMABsAjgBMABsAjgBMABsAGgBNABsAGgBNABsAHABLAEMAHABMAEMAjgBMAEMAjgBMAEMAHABLAEQAHABLAEQA", turret: "hABiAEkAhABiAEkAhQBeAEoAhQBeAEsAhQBiAEoAhQBiAEsAhQBjAEsAhQBjAEsAhQBmAEsAhQBnAEsAhgBnAEsAhgBnAE0AhgBeAEwAhgBfAEwAhgBjAEwAhgBjAEwAhgBeAE0AhgBeAE0AhgBgAE0AhgBgAE0AhgBiAE0AhgBiAE0AhgBkAE0AhgBkAE0AhgBmAE0AhgBmAE0AegBNAHgAegBNAHgAZABPAIEAbQBPAIEA", gun: "hABYAFEAkQBYAGcAhQBdAFEAiQBjAGMAjQBdAFEAkQBjAGMAhABeAFEAhABiAGMAigBeAFEAigBiAGMAjABeAFEAjABiAGMAkgBeAFEAkgBiAGMAhgBeAGQAiABiAI8AjgBeAGQAkABiAI8AhQBfAGQAhQBhAI8AiQBfAGQAiQBhAI8AjQBfAGQAjQBhAI8AkQBfAGQAkQBhAI8ATgBXAHUAXABYAHUATgBXAHYAXABXAHYATwBXAHcAXABXAHcAhgBeAJEAiABeAJcAjgBeAJEAkABeAJcAhQBfAJEAhQBhAJcAiQBfAJEAiQBhAJcAjQBfAJEAjQBhAJcAkQBfAJEAkQBhAJcAhgBiAJEAiABiAJcAjgBiAJEAkABiAJcA" },
});
