// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t62mv1": { v: 0.025, o: [-1.89, 0.265, -3.605], t: [0, 1.4804, 0.676], g: [0, 1.767, 1.695], hull: "HAAtABIALAAtABIAMwAtABIARwAtABIATwAtABIAYwAtABIAagAtABIAegAtABIAHAAwABcASAAwABgATwAwABcAegAwABgAIgAlAC8AIgApAC8AIgAoADAAIgApADAACwArAPUACwAtAPUADAArAPcADAAtAPcADQAsAPkADQAsAPkAIgAZAAMBIgAdAAMB", turret: "JABTAKIAJABTAKIANABUAKcAOABUAKsAaQBTAKgAaQBUAKgANABTAKkANABTAKsAaQBWAKoAaQBWAKoANQBTAKsANQBTAKsAGAA/ALYAGAA/ALYAfgA/ALYAfgA/ALYA", gun: "OwBJAM0AOwBJANEASABKANUASABKANUA" },
  "t64bv1": { v: 0.025, o: [-1.8655, 0.322, -3.43535], t: [0, 1.4571, 0.065591], g: [0.00605, 1.75875, 1.09655], hull: "dwAmAOkAdwAmAOkA" },
});
