// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "kv2": { v: 0.025, o: [-1.7345, -0.02, -3.69], t: [0, 1.67, 0.32], hull: "KgA4AOgAVQA5AOkAXAA4AOgAXwA9AOkAKgA6AOgAKwA9AOkAPAA6AOgAUwA9AOkAYAA8AOgAYQA9AOkALAA4AOoAUwA5AO0AXAA4AOoAXwA5AOsAPAA6AOoAUwA7AOsAXgA6AOoAXwA7AOsAXAA4AOwAXQA5AO8ALgA4AO4AVQA5AO8AMgAkAAwAMgAsAA0AVwAkAAwAWAAsAA0AKAA4AOcAYgA4AOcAKQA5AOcAYQA8AOcAHwA+AOcAKgA+AOcALQA+AOcAagA+AOcAVgA4AOgAWwA5AOgALQA8AOgAOwA9AOgAHwA9AOgAKAA9AOkAYgA9AOgAagA9AOkALAA6AOoAOwA6AO4APAA8AOoAUwA8AOoALAA7AOsAOwA7AOwAPAA6AOwAUwA7AOwAPAA6AO0AUwA6AO4AKgA3AO4AYAA3AO4AVwA4AO4AWgA4APEAKwA3AO8AXwA3AO8ALAA3APAAXQA3APAALgA4APAAVQA5APAALQA3APEAXQA3APEALgA4APEAVQA4APEALgA3APIAWwA3APIALwA3APMAWwA3APMA" },
});
