// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t62mv1_x": { v: 0.025, o: [-1.725, 0.302, -3.659563], t: [0, 1.446436, 0.304185], g: [0, 1.665042, 1.530375], hull: "KQAkABMAPAAkABMAPgAkABMAQwAkABMARgAkABMASwAkABMATQAkABMAYQAkABMAPwAlABYAQwAlABYARgAlABYASgAlABYAPwAmABcAQwAmABcARgAmABcASgAmABcAPgAnABgAQwAnABgARgAnABgASwAnABgAPgAoABkAQwAoABkARgAoABkASwAoABkAPgArABsAQwArABsARgArABsASwArABsACgAkAHgACgAmAHgAIAAkAHgAIAAoAHgAaQAkAHgAaQAoAHgAgAAkAMIAgAAmAMIAGwAkAOkAHwAkAOkAagAkAOkAbgAkAOkAHwAkAOoAHwAkAOoAagAkAOoAagAkAOoAaQAlAOoAaQAlAOoA", turret: "XwA4AHUAXwA9AHUAKQA6AHYAKgA6AHYAKgA7AHYAKwA9AHYAWgA9AHYAWwA9AHYAOgBJAJcAOgBJAJcAUQBJAJgAUQBJAJgANQBJAKAANQBJAKAAJwBFAKEAJwBFAKEAMQBJAKIAMQBJAKIAZgBCALkAZgBCALkASAAvAMAATQBAAMAASAAvAMEATQA/AMEASQAvAMIATQA7AMMASQA8AMIATAA/AMIATQA+AMIATQA/AMIASQA8AMMASwA/AMMATAA+AMMATAA/AMMATQA/AMMATQA/AMMASgAvAMQATQA7AMQASgA8AMQATAA+AMQATQA+AMQATQA+AMQA" },
});
