// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t62mv1_x": { v: 0.025, o: [-1.725, 0.302, -3.6596], t: [0, 1.4464, 0.3042], hull: "KQAkABMAPAAkABMATgAkABMAYQAkABMA", turret: "SAAwAMAATQA/AMEASgAwAMIATQA7AMMASgA8AMIASwA/AMMASAAvAMAATQAvAMEASQAwAMIASQA/AMMASgAvAMQATQA7AMQA" },
});
