// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t62mv1_x": { v: 0.025, o: [-1.89, 0.265, -3.605], t: [0, 1.4804, 0.676], g: [0, 1.697127, 1.977307], hull: "HAAtABIALAAtABIAMwAtABIARwAtABIATwAtABIAYwAtABIAagAtABIAegAtABIAHAAwABcASAAwABgATwAwABcAegAwABgAIgAlAC8AIgApAC8AIgAoADAAIgApADAACwArAPUACwAtAPUADAArAPcADAAtAPcADQAsAPkADQAsAPkAIgAZAAMBIgAdAAMB" },
});
