// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t72b3m": { v: 0.025, o: [-1.875, 0.025, -4.696], t: [0, 1.46, -0.65], hull: "IAAiAB4AIQAjAB8AdAAoAB4AdQAtACEAIAAkACAAIQAtACEAdAAmACAAdQAnACEAIAAsACIAIQAtACUAdAAsACIAdQAtACUAEAAsACoAEQAtACsAGgAiADwAGwAnAOkAegAiADwAewAnAOkAegAoAMoAewAtAM0AGgAoAMwAGwAtAM8AjAAqAAoBjQArAAsBDgAqAAwBHQArAA0BdgAqAAwBhQArAA0BJAAwAAcAcQA6AAgAcwAqAB0AcwAuACEAdgAlAB4AdwAuAB4AIgAmAB4AIgAuACIAdAAuAB4AdQAuACYAIAAuACAAIQAuACYAIAAlACIAIQArACIAcwArACIAdQArACYAcwAsACIAcwAuACYAIAArACMAIgArACYAIgAsACMAIgAuACYAEgAiAC4AEgAjADQAgwAiAC4AgwAjADQAGgAhADsAGwAoADsAegAhADsAewAoADsAGgAhADwAGwAhAOkAegAhADwAewAhAOkAGgAoADwAGwAoAMsAegAoADwAewAoAMkAegAoAM4AewAoAOkAGgAoANAAGwAoAOkAEgAiAPQAEgAjAPkAgwAiAPQAgwAjAPkAIgAsAPkAIgAuAPwAcwAsAPkAcwAuAPwADgAsAAMBHwAsAAQBdgAsAAMBhgAsAAQBHgAqAAkBIQAsAAkBDgAsAAwBHQAsAA0BdgAsAAwBhQAsAA0B", turret: "FgBEAGoAFwBFAHcAFABEAGwAFQBFAHEAEgBEAG4AEwBFAHEAJABKAIoAJwBLAI0AeABFAHIAeQBFAHgAIgBJAIgAKABKAIgAIwBJAIkAKABQAIkAIwBSAIkAKABTAIkAIwBJAIoAKABJAI0A" },
  "t72bu": { v: 0.025, o: [-1.96, 0.225, -3.515], t: [0, 1.42, 0.16], hull: "jAAuABwAjQAvAB0AHAAoANwAHQApAN0ARgAmAOQASwAnAOcAUAAmAOQAVQAnAOcACAAnANkACAApAOMARgAnAOEATAAnAOMAUAAnAOEAVgAnAOMAVgAmAOQAWAAmAOcACAAnAOYACAApAPsA", turret: "QgBCAJwAQwBDAJ0ARABBAIsARABBAJcAQwBCAJoARABEAJsA" },
});
