// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t72b3m": { v: 0.025, o: [-2.03, 0.37761, -3.545], t: [0.008, 1.545, 0.114315], g: [0.001, 1.91609, 1.315315], gun: "TgBIALkAUwBIAMAATABIALoATQBIAMAAVABIALoAVQBIAMAARgBHALsAXwBHAMEAVgBIALsAVwBIAMAASQBHAMIAWQBHAMIAUwBFAMYAXgBFAMYA" },
  "t72bu": { v: 0.025, o: [-1.805, 0.27235, -3.382], t: [0.004898, 1.330328, 0.248077], g: [0.002246, 1.629789, 1.370949] },
});
