// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t72b_1987_x": { v: 0.025, o: [-1.7935, 0.3449, -3.995], t: [-0.0001, 1.4041, -0.0343], hull: "HgAfAPoAHgAfABUBcQAfAPoAcQAfABUBHgAeAPwAHgAeABgBcQAeAPwAcQAeABgBHgAdAP8AHgAdABgBcQAdAP8AcQAdABgBHgAcAAEBHgAcABgBcQAcAAEBcQAcABgBHgAbAAQBHgAbABgBcQAbAAQBcQAbABgBHgAaAAYBHgAaABgBcQAaAAYBcQAaABgBHgAZAAgBHgAZABgBcQAZAAgBcQAZABgBHgAYAAsBHgAYABgBcQAYAAsBcQAYABgBHgAXAA0BHgAXABgBcQAXAA0BcQAXABgB", turret: "egAyAJwAegA/AJwA" },
});
