// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "t80u_x": { v: 0.025, o: [-1.875, -0.0012, -3.5996], t: [0, 1.5516, 0.0719], hull: "CAA0AHYACQA5AIMAjAA0AHYAjQA5AIMACQAzAHYACQAzAIQAjAAzAHYAjAAzAIQABwA0AHYABwA0AIQAjgA0AHYAjgA0AIQACAA0AIQACQA5AIQAjAA0AIQAjQA5AIQAIQA3AOYAIQA3APcAdAA3AOYAdAA3APcAIQA2AOgAIQA2AAMBdAA2AOgAdAA2AAMBIQA1AOoAIQA1AAMBdAA1AOoAdAA1AAMBIQA0AOwAIQA0AAMBdAA0AOwAdAA0AAMBIQAzAO4AIQAzAAMBdAAzAO8AdAAzAAMBIQAyAPEAIQAyAAMBdAAyAPEAdAAyAAMBIQAxAPQAIQAxAAMBdAAxAPQAdAAxAAMBJgAxAPUAKwA1APYAagAxAPUAbwA1APYAIQAwAPcAIQAwAAMBdAAwAPcAdAAwAAMBOwAvAPoAWgAvAPsA" },
});
