// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "tos1a_tagil": { v: 0.025, o: [-1.96555, 0.362, -3.87675], t: [-0.00095, 1.5455, 0.118], g: [-0.00095, 2.8455, -1.182], hull: "MAAgABgAMQAhABkAWgAgABgAWwAhABkAXgAgABgAXwAhABkAbAAgABgAbQAhABkAcAAgABgAcQAhABkADQApACEAIAApACIADQArACMAIAArACMAeAAUADgAeAAkADgAeAAQAEgAeAArAEgAeQAVAFoAeQAmAFoAIwAUAF8AIwAeAGIAIwAiAF8AIwAmAGIAmAAjAGIAmAAjAHEAeQAQAMMAeQAkAMMAJAAjAPkAKAAjAP8AdAAjAPkAeAAjAAUBJAAiAPwAKAAiAP8AdAAiAPwAeAAiAAUBJgAgAAABKAAjAAsBdAAgAAABeAAhAAUBJQAgAAEBJQAjAAwBJQAfAAMBKAAfABEBdAAfAAMBeAAfAAUBeAAQAAUBeAAcAAUBJQAeAAYBKAAeABEBdAAeAAYBdwAjAAsBJQAdAAcBKAAdABEBdAAdAAcBdwAdABEBJQAcAAoBKAAcABEBdAAcAAoBdwAcABEBdAAeAAwBdwAhABEBJgAgAAwBKAAhABEBKAAiAAwBKAAjAAwBJQAgAA0BJQAiABEBJgAiAA0BKAAiABEBdAAiAA0BdwAiABEBJgAaAA4BJwAbABEBdAAaAA4BdwAbABEB", turret: "igA5AGcAigA5AHUADwBZAHEADwBbAHQAjQBZAHEAjQBbAHQA", gun: "GABgAEcAGQBlAGMAgwBgAEcAhABlAGMAFwBiAEcAFwBkAGMAGQBmAEcAGQBmAGQAgwBmAEcAgwBmAGQAhQBhAEgAhQBkAGMAgwBhAGUAgwBkAHEAgwBgAGYAgwBgAHEAgwBlAGYAgwBmAHEAjAA7AGgAjABOAG8AEAA6AIwAEQA6AJIA" },
});
