// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame / gun frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "type10_x": { v: 0.025, o: [-1.769649, 0.293319, -3.86625], t: [-0.00276, 1.50832, 0.20655], g: [0, 1.851, 2.0529], hull: "JgAsAAQAOAAsAAkAOgAsAAQATgAsAAkAUAAsAAQAZgAsAAkAOQAaAAcAOQAsAAgATwAaAAcATwAsAAgAOQAbAAkAOQAsAAkATwAbAAkATwAsAAkAOQAbAAoAOQAlAAoATwAbAAoATwAlAAoAOQAbAAsAOQAcAAsATwAbAAsATwAcAAsACwAkAAsACwArAAsACwAdABQAIgAiABcAawAdABQAgQAiABcACwAkABQAIgAsABcAawAkABQAgQAsABcAIAAeABgAIgAiABgAawAeABgAbQAiABgAIAAkABgAIgAsABsAawAkABgAbQAsABsACwAoABgAHwAsABsAbgAoABgAgQAsABsAIAAhABkAIgAiABkAawAhABkAbQAiABkAagArAN8AagArAOAAagAdACABagAiACABagAdACEBagAhACMBMgAUACIBNQAUACYBWAAUACIBWAAUACYBWgAUACIBWgAUACYBMgAVACMBNQAVACYBWAAVACMBWgAVACYBagAdACQBagAgACUBagAdACYBagAfACYBagAeACcBagAfACcBagAfACgBagAfACgB", turret: "TABMAE8ATABQAFAATgBMAE8ATgBPAFAARgBMAFAARwBRAFAATQBMAFAATQBRAFAATgBQAFAATgBRAFAATABRAFAATABRAFAARgBMAFEARwBMAGIATABMAFEATgBMAGIATABSAF4ATABSAGEATABMAGMATABRAGMAWQBOAL0AaQBOAMwA" },
});
