// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "type90_x": { v: 0.025, o: [-1.8839, 0.372, -4.1195], t: [0, 1.6817, 0.157], hull: "IgAkABIAIwAnABUAdAAmABIAdQAnABUAIgAkABYAIwAlABkAGAAqACwBGQArAC0BIwAiABIAIwAjABgAcwAiABIAcwAnABYAdAAkABIAdAAlABgAIQAlABIAIQAnABYACgAfABkAIgAfABkAcwAfABkAjAAfABkAJAAeACMBJAAjACwBcQAeACMBcQAjACwBcgAgACMBcgAjACwBfQApACwBggArACwB", turret: "SABCAE4ATQBDAFEASABGAE4ATQBHAFMATABEAFAATQBFAFEATABIAFAATQBLAFEAHQBBAEMAdABBAEMASABBAE4ATQBBAE8ASABIAE4ATQBIAE8ASABIAFAASwBIAFMASABCAFIATQBDAFIA" },
});
