// Generated by tools/gen-interior-fills.mjs. Do not hand-edit.
// Interior fill boxes per tank (base64 little-endian Uint16 sextets of inclusive fine-voxel spans, hull frame /
// turret frame): buried solids that make the body watertight. Regenerate after any playable geometry change.
import type { InteriorFillRecord } from '../interiorFills.ts';

export const INTERIOR_FILLS: Readonly<Record<string, InteriorFillRecord>> = Object.freeze({
  "tiger1": { v: 0.025, o: [-1.931, -0.045, -3.48], t: [0, 1.96, 0.25], hull: "IgAwACgAdwAzAO0AIgAwAO4AdwAxAO8ALQBTABAAMgBVABAAPABTABAAQQBeABAAWQBTABAAWwBeABAAaABTABAAbQBVABAAXABVABAAXgBeABAALgBTABcALgBVABoAIgAzAB8AdwAzACIAIgAvACcAdwAzACcAIgAvACgAdwAvAO8APQBTADAATABUADAAIgAyAO4AdwAzAO4AIgAyAO8AdwAyAO8A", turret: "ZQBZAEwAZQBnAEwA" },
});
