// Generated by tools/record-town-plan.mjs from PR #9's head 0bbb0cddc (the maps-and-layouts lane, 2026-10-03; the owner's
// town-plan ruling): each rebuilt battlefield's settlement exactly as that build seated it. Every entry is one planned
// building: its structure, its plan index, its wall, the props stream's state after the wall pick, and its final pose
// (props.ts townPlan). Do not edit by hand.
import type { TownPlanEntry } from '../props.ts';

export const TOWN_PLANS: Readonly<Record<string, readonly TownPlanEntry[]>> = {
  titan_gorge: [
    { structure: 'caravanserai', planIndex: 0, wall: 'plaster3', rng: 567896475, x: -112.802208, z: 48.629518, rot: 0.439703623 },
    { structure: 'compound', planIndex: 1, wall: 'stone', rng: -1415195338, x: 58.733968, z: -50.221127, rot: 0.55398954 },
    { structure: 'depot', planIndex: 2, wall: 'plaster', rng: 299395178, x: 73.870945, z: -23.443414, rot: 0.516964292 },
    { structure: 'ruin', planIndex: 3, wall: 'stone', rng: -1355499644, x: 46.158901, z: -6.485298, rot: 0.575264659 },
    { structure: 'marketRow', planIndex: 4, wall: 'plaster', rng: -2122794008, x: 87.648054, z: 4.961639, rot: 0.571434425 },
    { structure: 'watertower', planIndex: 5, wall: 'plaster', rng: -776698074, x: 61.217676, z: 21.135452, rot: 0.583690596 },
    { structure: 'adobe', planIndex: 6, wall: 'plaster2', rng: -656391980, x: 106.949172, z: 29.986328, rot: -1.021643424 },
    { structure: 'compoundSouk', planIndex: 7, wall: 'plaster2', rng: 1780035100, x: 128.675327, z: 19.738428, rot: -0.567394938 },
    { structure: 'factory', planIndex: 8, wall: 'stone', rng: 335447266, x: 111.974423, z: 46.526131, rot: -0.495737245 },
    { structure: 'ruin', planIndex: 9, wall: 'plaster2', rng: -902164377, x: 94.610828, z: 72.924016, rot: -0.572120581 },
    { structure: 'containerRow', planIndex: 10, wall: 'plaster2', rng: 730001545, x: 102.621341, z: 114.451482, rot: -0.546229016 },
    { structure: 'minaret', planIndex: 11, wall: 'stone', rng: 1075767227, x: 78.247117, z: 99.646397, rot: -0.574568044 },
    { structure: 'depot', planIndex: 12, wall: 'plaster', rng: -1267328162, x: 87.436464, z: 142.470619, rot: -0.561568409 },
    { structure: 'warehouse', planIndex: 13, wall: 'plaster', rng: 1436685509, x: 62.743977, z: 126.991747, rot: -0.542972692 },
    { structure: 'compound', planIndex: 14, wall: 'plaster2', rng: -713084904, x: 115.71183, z: -35.704764, rot: 1.546274171 },
    { structure: 'ruin', planIndex: 15, wall: 'plaster', rng: 1129388006, x: 138.140902, z: -69.413019, rot: 1.792964067 },
    { structure: 'gantry', planIndex: 16, wall: 'plaster', rng: 1561823785, x: 144.821292, z: -38.874096, rot: 1.744970821 },
    { structure: 'marketRow', planIndex: 17, wall: 'plaster2', rng: 666647027, x: -126.330171, z: -120.498905, rot: 1.560193487 },
    { structure: 'caravanserai', planIndex: 18, wall: 'plaster3', rng: 60871054, x: -44.043166, z: -122.04066, rot: 1.580915418 },
    { structure: 'adobe', planIndex: 19, wall: 'plaster3', rng: -2097977044, x: -18.228427, z: -119.891663, rot: -0.014991151 },
    { structure: 'watertower', planIndex: 20, wall: 'stone', rng: 2061531558, x: 39.259652, z: -122.47984, rot: 0.012106178 },
    { structure: 'ruin', planIndex: 21, wall: 'plaster2', rng: 982107509, x: 62.110152, z: -114.354482, rot: 1.572833109 },
    { structure: 'factory', planIndex: 22, wall: 'plaster2', rng: -793093407, x: 87.576964, z: -116.910031, rot: -0.024646345 },
    { structure: 'depot', planIndex: 23, wall: 'plaster2', rng: 1128473300, x: 92.110528, z: -90.677651, rot: 1.541782086 },
    { structure: 'containerRow', planIndex: 24, wall: 'plaster', rng: 1868793261, x: 117.93331, z: -61.831408, rot: -0.022413331 },
    { structure: 'compoundSouk', planIndex: 25, wall: 'plaster', rng: 431781727, x: -100.190103, z: -35.466036, rot: 1.581048037 },
    { structure: 'warehouse', planIndex: 26, wall: 'plaster', rng: 1307560382, x: 94.638365, z: -41.614902, rot: 1.557644671 },
    { structure: 'ruin', planIndex: 27, wall: 'stone', rng: -290969543, x: -127.754263, z: -8.863752, rot: 1.585317415 },
  ],
};
