// Generated by tools/record-town-plan.mjs from PR #9's head 0bbb0cddc (the maps-and-layouts lane, 2026-10-03; the owner's
// town-plan ruling): each rebuilt battlefield's settlement exactly as that build seated it. Every entry is one planned
// building: its structure, its plan index, its wall, the props stream's state after the wall pick, and its final pose
// (props.ts townPlan). Do not edit by hand.
import type { TownPlanEntry } from '../props.ts';

export const TOWN_PLANS: Readonly<Record<string, readonly TownPlanEntry[]>> = {
};
