// Generated by tools/wreck-bake-plan.mjs — do not edit. The wreck bakes each map's props build requests of the
// wreck worker, in order: [donor spec, seed, ammo-rack pop]. The world build starts them beside the terrain and
// vegetation (src/world/wreckBakePrefetch.ts); any other request bakes on demand.
type WreckBakeRows = ReadonlyArray<readonly [string, number, 0 | 1]>;
/** Every map: the desktop tier on the standard terrain. */
export const WRECK_BAKE_PLAN: Readonly<Record<string, WreckBakeRows>> = {
  airfield: [['t72b3_x', 2002, 1], ['t72b3_x', 2133, 0], ['t80bv', 2264, 1], ['t80bv', 2395, 0], ['bmp2', 2526, 0], ['ua_t64bv', 2657, 1]],
  alpine: [],
  autumn: [],
  badlands: [['challenger1', 2002, 1], ['m60a3', 2133, 1], ['chieftain5', 2264, 1], ['centurion5', 2395, 0], ['challenger1', 2526, 0], ['m60a3', 2657, 0]],
  blackglass: [],
  caldera: [['type10', 2002, 1], ['type90', 2133, 0], ['type74', 2264, 1], ['type89', 2395, 1], ['type74', 2526, 0]],
  cliffbridge: [['amx30_x', 2002, 1], ['m48', 2133, 0], ['m47_patton', 2264, 1], ['amx30_x', 2395, 0]],
  coastal: [['leclerc', 2002, 1], ['t90m', 2133, 1], ['cv90', 2264, 1], ['bmp3', 2395, 1], ['leo2a7v', 2526, 1]],
  copper_mesa: [['centurion5', 2002, 1], ['centurion5', 2133, 0], ['leo1a5', 2264, 1], ['leo1a5', 2395, 0]],
  delta: [['type59', 2002, 1], ['type59', 2133, 0]],
  desert: [['m60a3', 2002, 1], ['type59', 2133, 1], ['m48', 2264, 1], ['t62mv1', 2395, 1], ['m60a3', 2526, 0]],
  fjord: [],
  foundry: [],
  frontier: [['m60a3', 2002, 1], ['m1a1', 2133, 1], ['leo1a5', 2264, 1], ['marder1a3', 2395, 1], ['t80b', 2526, 1], ['t80b', 2657, 0], ['bmp2', 2788, 0]],
  longleaf: [],
  mangrove: [['type59', 2002, 1], ['type59', 2133, 0], ['bmp2', 2264, 1], ['t62mv1', 2395, 1], ['t62mv1', 2526, 0], ['m48', 2657, 1]],
  mars: [['abramsx', 2002, 1], ['t14', 2133, 0], ['challenger_3', 2264, 1], ['m1a3', 2395, 0], ['kf51', 2526, 0]],
  monsoon: [],
  moon: [],
  oasis: [['m60a3', 2002, 1], ['m60a3', 2133, 0], ['m1a1', 2264, 1], ['t62mv1', 2395, 1], ['type59', 2526, 0]],
  orchard: [['merkava1b', 2002, 1], ['merkava1b', 2133, 0], ['m60a1', 2264, 1], ['centurion5', 2395, 1], ['t62mv1', 2526, 0], ['t62mv1', 2657, 1], ['t72m1_jaguar', 2788, 0]],
  polders: [],
  railyard: [['m48', 2002, 1], ['centurion5', 2133, 1], ['m47_patton', 2264, 0], ['centurion5', 2395, 0]],
  reservoir: [],
  ruinspires: [['t72m1_jaguar', 2002, 1], ['type59', 2133, 1], ['bmp2', 2264, 0], ['t72m1_jaguar', 2395, 0], ['type59', 2526, 0]],
  saltwind: [['t72m1_jaguar', 2002, 1], ['t72m1_jaguar', 2133, 0], ['type59', 2264, 0], ['bmp2', 2395, 0], ['type59', 2526, 1]],
  skybridge: [['m48', 2002, 1], ['m60a1', 2133, 1], ['m60a1', 2264, 0], ['m47_patton', 2395, 1], ['m551_sheridan', 2526, 1], ['m551_sheridan', 2657, 0], ['m48', 2788, 0], ['m47_patton', 2919, 0]],
  steppe: [['type59', 2002, 1], ['type59', 2133, 0]],
  titan_gorge: [['m60a1', 2002, 1], ['m48', 2133, 0], ['m551_sheridan', 2264, 1], ['m47_patton', 2395, 1], ['m47_patton', 2526, 0], ['m60a1', 2657, 0], ['m48', 2788, 1], ['m551_sheridan', 2919, 0]],
  urban: [['leo2a4', 2002, 1], ['t72m1_jaguar', 2133, 1], ['t72m1_jaguar', 2264, 0], ['marder1a3', 2395, 0], ['bmp2', 2526, 1], ['bmp2', 2657, 0], ['leo1a5', 2788, 1], ['m1a1', 2919, 1]],
  verdant: [['kv2', 2002, 1], ['kv2', 2133, 0]],
  whiteout: [['leo1a5', 2002, 1], ['leo1a5', 2133, 0], ['m48', 2264, 1], ['strv103', 2395, 0], ['t80b', 2526, 0], ['bmp2', 2657, 1], ['bmp2', 2788, 0]],
  winter: [],
};
/** Where a variant's requests differ from its fallback (resolveWreckBakeRows): <map>@mobile, @assault, @assault-mobile. */
export const WRECK_BAKE_PLAN_VARIANTS: Readonly<Record<string, WreckBakeRows>> = {
  'coastal@assault': [['leclerc', 2002, 1], ['t90m', 2133, 1], ['cv90', 2264, 1], ['bmp3', 2395, 1], ['bmp3', 2526, 0], ['leo2a7v', 2657, 1]],
  'coastal@assault-mobile': [['leclerc', 2002, 1], ['t90m', 2133, 1], ['cv90', 2264, 1], ['bmp3', 2395, 1], ['bmp3', 2526, 0], ['leo2a7v', 2657, 1]],
  'orchard@assault': [['merkava1b', 2002, 1], ['merkava1b', 2133, 0], ['m60a1', 2264, 1], ['centurion5', 2395, 1], ['t62mv1', 2526, 0], ['t72m1_jaguar', 2657, 1]],
  'orchard@assault-mobile': [['merkava1b', 2002, 1], ['merkava1b', 2133, 0], ['m60a1', 2264, 1], ['centurion5', 2395, 1], ['t62mv1', 2526, 0], ['t72m1_jaguar', 2657, 1]],
};
