// Generated by tools/wreck-bake-plan.mjs — do not edit. The wreck bakes each map's props build requests of the
// wreck worker (desktop tier, the standard terrain), in order: [donor spec, seed, ammo-rack pop]. The world build
// starts them beside the terrain and vegetation (src/world/wreckBakePrefetch.ts); any other request bakes on demand.
export const WRECK_BAKE_PLAN: Readonly<Record<string, ReadonlyArray<readonly [string, number, 0 | 1]>>> = {
  monsoon: [['type99a', 2002, 1], ['type99a', 2133, 0], ['type10', 2264, 1], ['k1a1', 2395, 0], ['type90', 2526, 0], ['type90', 2657, 1], ['k2', 2788, 1], ['bmp3', 2919, 0], ['m2a2_bradley', 3050, 0]],
  titan_gorge: [['m60a2', 2002, 1], ['merkava4b', 2133, 1], ['merkava4b', 2264, 0], ['m60a3', 2395, 1], ['ariete', 2526, 1], ['t72b3m', 2657, 0], ['m1a2', 2788, 0]],
  verdant: [['m551_sheridan', 2002, 1], ['marder1a3', 2133, 1], ['leo2a7v', 2264, 1], ['m1a1', 2395, 1], ['t90a', 2526, 1], ['t90a', 2657, 0]],
};
