#!/usr/bin/env node
// tools/skybridge-arm.mjs — Skybridge Chasm's reservoir arm, computed once (the map-revival lane, 2026-10-08, round 6):
// writes src/world/maps/skybridgeArm.generated.ts from skybridgeArm.ts's computeSkybridgeArm(), so the map config reads
// the arm's course, water discs, boulders, kerbs and dam site as data and fits nothing as the map configs load.
//   node tools/skybridge-arm.mjs           write the generated file
//   node tools/skybridge-arm.mjs --check   exit 1 when the generated file differs from a fresh computation
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGET = join(ROOT, 'src/world/maps/skybridgeArm.generated.ts');
const { computeSkybridgeArm } = await import(join(ROOT, 'src/world/maps/skybridgeArm.ts'));

export function renderSkybridgeArm() {
  const data = computeSkybridgeArm();
  return `// src/world/maps/skybridgeArm.generated.ts — GENERATED by tools/skybridge-arm.mjs from skybridgeArm.ts; do not edit.
// Skybridge Chasm's reservoir arm as data (round 6): its course and widths, side canyons, landforms, water discs, the
// boulders on the head's brow and the dam's site. Regenerate after any change to skybridgeArm.ts
// (skybridgeArm.selftest.mjs fails while they differ).
import type { SkybridgeArmData } from './skybridgeArm.ts';

export const SKYBRIDGE_ARM = ${JSON.stringify(data)} as unknown as SkybridgeArmData;
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = renderSkybridgeArm();
  if (process.argv.includes('--check')) {
    const current = readFileSync(TARGET, 'utf8');
    if (current !== text) { console.error('skybridgeArm.generated.ts is stale: run node tools/skybridge-arm.mjs'); process.exit(1); }
    console.log('skybridgeArm.generated.ts is current');
  } else {
    writeFileSync(TARGET, text);
    console.log(`wrote ${TARGET} (${text.length} bytes)`);
  }
}
